---
permalink: windows/concept-what-snapmanager-for-oraclesnapmanager-for-sap-does.html 
sidebar: sidebar 
keywords: snapmanager, sap, simplify, simplifies, automate, database, backup, recovery, clone, leverage, snapshot, copies, copy, snaprestore, flexclone, technology, technologies 
summary: SnapManager for SAP利用Snapshot副本、SnapRestore 和FlexClone技术简化并自动执行数据库备份、恢复和克隆。 
---
= SnapManager for SAP的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager for SAP利用Snapshot副本、SnapRestore 和FlexClone技术简化并自动执行数据库备份、恢复和克隆。

SnapManager 为数据库管理员（ Database Administrator ， DBA ）提供了以下优势：

* 使用数据库配置文件
+
** 您可以在配置文件中组织和保留主机和数据库信息。
+
在基于配置文件启动备份时，您可以重复使用此信息，而不必为每次备份重新输入此信息。此外，您还可以通过 SnapManager 使用配置文件快速监控操作。

** 在配置文件中，您可以定义 Snapshot 副本的命名模式并输入自定义（前缀或后缀）文本，以便所有 Snapshot 副本都可以使用符合业务策略的相同命名约定。
** 您无需知道存储系统名称，因为数据库文件会自动映射到关联的存储。
** 创建新配置文件时，您可以指定将归档日志备份与数据文件备份分开的选项。
+
您还可以更新现有配置文件，以便将归档日志备份与数据文件备份分开。



* 执行数据库备份操作
+
** 备份完整和部分数据库
+
*** 您可以以节省空间的方式快速创建完整备份或部分备份，从而可以更频繁地执行备份。
+
完整的数据库备份将所有数据文件，控制文件和归档日志文件都包含在一个备份中。

+
部分数据库备份包含指定的数据文件或表空间，所有控制文件和所有归档日志文件。

*** 您可以使用后处理脚本保护到二级存储的备份。
*** 您可以按每小时，每周，每天，每月或无限制计划备份。


** 单独备份数据文件和归档日志文件
+
*** 通过 SnapManager （ 3.2 或更高版本），您可以分别备份数据文件和归档日志文件。要执行此操作，您必须指定在创建或更新配置文件时分隔归档日志文件的选项。
*** 您可以在保留策略中指定要保留数据文件备份的计数和持续时间。
*** 您可以指定归档日志文件备份在归档日志保留期限内保留的持续时间。
*** SnapManager （ 3.2 或更高版本）还可以释放具有重复归档日志文件的归档日志备份，并仅保留具有唯一归档日志文件的归档日志备份，从而将归档日志备份整合为最少数量的备份。但是，可以选择禁用此整合。




* 管理归档日志文件
+
** 通过 SnapManager （ 3.2 或更高版本），您可以从归档日志目标位置对归档日志文件进行修剪。
+
清除包含这些归档日志文件的归档日志备份后，会释放经过修剪的归档日志文件占用的空间。

** SnapManager 可确保先备份归档日志文件，然后再将其从归档日志目标中删除。
+
未备份的归档日志文件不会进行修剪。

** SnapManager 可确保将归档日志文件发送到数据防护备用数据库，同时从数据防护主数据库中删除归档日志文件。
** SnapManager 可确保归档日志文件通过 Oracle 的流捕获进程（如果有）捕获。
** 建议
+
*** 要有效管理归档日志目标空间，您必须创建归档日志备份，并对归档日志文件及其进行修剪。


** SnapManager 通过释放具有重复归档日志文件的归档日志备份，并仅保留具有唯一归档日志文件的归档日志备份，从而整合归档日志备份，以包含最少数量的备份。
+
但是，可以选择禁用此整合。将释放包含重复归档日志文件的归档日志备份，并保留具有唯一归档日志的单个备份。



* 执行数据库还原操作
+
** 您可以执行基于文件的还原操作。
+
在执行还原操作之前，您还可以预览还原操作并获取还原操作的文件分析。

** 您可以使用 SnapRestore 缩短恢复数据库的平均时间。
** 通过 SnapManager （ 3.2 或更高版本），您可以使用备份中的归档日志文件自动恢复数据库，即使归档日志文件在归档日志目标中不可用也是如此。
+
SnapManager （ 3.2 或更高版本）还提供了一种在一定程度上使用外部位置的归档日志文件来恢复数据库的方法。



* 为测试和开发执行数据库克隆
+
** 您可以创建数据库的克隆，以便在生产环境之外设置数据库。
+
例如，您可以在开发和测试环境中进行克隆，以测试对重要系统的升级。

** 您可以克隆主存储系统上的数据库。
** 通过 SnapManager （ 3.2 或更高版本），您可以使用备份中提供的归档日志文件克隆数据文件备份。
+
*** 只有在与归档日志备份一起进行时，才能克隆数据文件备份。
*** 如果归档日志文件在特定范围内单独创建的归档日志备份中可用，则也可以克隆数据文件备份。
*** 您还可以使用 Oracle 可访问的任何外部位置的归档日志文件在一定程度上克隆独立数据库的数据文件备份。
*** 如果可以从外部位置进行备份，则可以在克隆期间指定外部位置，以便将克隆的数据库恢复到一致状态。


** 不支持克隆仅归档日志备份。


* 常规
+
** 与SAP的Br*工具集成。
+
BR*工具包可提供SAP工具、例如BRARCHIVE、BRBACKUP、BRCONNECT、BRRECOVER、BRRESTORE、 BRSPACE和BRTOOLS。





SnapManager 为存储管理员提供了以下优势：

* 支持不同的 SAN 协议。
* 用于根据最适合您环境的备份类型（完整或部分）优化备份。
* 创建节省空间的数据库备份。
* 创建节省空间的克隆。


SnapManager 还支持以下 Oracle 功能：

* SnapManager 可以使用 Oracle 的 RMAN 对其备份进行编目。
+
如果使用 RMAN ， DBA 可以利用 SnapManager 备份并保留所有 RMAN 功能的值，例如块级还原。SnapManager 允许 RMAN 在执行恢复或还原时使用 Snapshot 副本。例如，您可以使用 RMAN 还原表空间中的表，并从 SnapManager 创建的 Snapshot 副本执行完整的数据库和表空间还原和恢复。RMAN 恢复目录不应位于要备份的数据库中。


