---
permalink: windows/concept-database-backup-management.html 
sidebar: sidebar 
keywords: snapmanager, enable, back up, data, local, storage, resource, post-process, script, database 
summary: SnapManager 支持使用后处理脚本备份本地存储资源上的数据。 
---
= 备份数据库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 支持使用后处理脚本备份本地存储资源上的数据。

SnapManager 提供了以下选项来备份，还原和恢复数据库中的数据：

* 备份整个数据库或其中一部分数据库。
+
如果您备份了其中一部分，请指定一组表空间或一组数据文件。

* 分别备份数据文件和归档日志文件。
* 将数据库备份到主存储（也称为本地存储），并通过使用后处理脚本将其备份到二级存储来对其进行保护。
* 计划例行备份。


* SnapManager （ 3.2 或更高版本）与早期 SnapManager 版本有何不同 *

通过 SnapManager （ 3.1 或更早版本），您可以创建包含数据文件，控制文件和归档日志文件的完整数据库备份。

SnapManager （ 3.1 或更早版本）仅管理数据文件。归档日志文件可使用 SnapManager 以外的解决方案进行维护。

SnapManager （ 3.1 或更早版本）在管理数据库备份时具有以下限制：

* 性能影响
+
在执行完整备份，联机数据库备份（当数据库处于备份模式时）时，数据库的性能会在创建备份之前的一段时间内下降。在 SnapManager （ 3.2 或更高版本）中，可以进行有限的数据库备份和频繁的归档日志备份。频繁进行归档日志备份有助于防止数据库置于备份模式。

* 手动还原和恢复
+
如果所需的归档日志文件不在活动文件系统中，数据库管理员必须确定哪个备份包含归档日志文件，挂载数据库备份并恢复还原的数据库。此过程非常耗时。

* 空间限制
+
创建数据库备份后，归档日志目标将变为已满，从而导致数据库在存储上创建足够空间之前无法响应。在 SnapManager （ 3.2 或更高版本）中，可以从活动文件系统中删减归档日志文件，以便定期释放空间。



* 为什么归档日志备份很重要 *

执行还原操作后，要将数据库前滚，需要使用归档日志文件。Oracle 数据库上的每个事务都会捕获到归档日志文件中（如果数据库处于归档日志模式）。数据库管理员可以使用归档日志文件还原数据库备份。

* 仅归档日志备份的优势 *

* 为仅归档日志备份提供单独的保留期限
+
恢复所需的仅归档日志备份的保留期限可以更短。

* 使用后处理脚本保护仅归档日志备份
* 提高数据库的性能
* 整合归档日志备份
+
SnapManager 会通过释放重复的归档日志备份来整合每次进行备份时的归档日志备份。


