---
permalink: windows/concept-variables-available-in-custom-script-for-restore-operation.html 
sidebar: sidebar 
keywords: snapmanager, context, information, form, environment, variable, restore, operation, perform, script, original, host, backup, restore 
summary: SnapManager 以与正在执行的还原操作相关的环境变量的形式提供上下文信息。例如，您的脚本可以检索原始主机的名称以及所还原备份的标签。 
---
= 可用于还原操作的任务脚本中的变量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapManager 以与正在执行的还原操作相关的环境变量的形式提供上下文信息。例如，您的脚本可以检索原始主机的名称以及所还原备份的标签。

下表列出了可在脚本中使用的环境变量：

|===
| 变量 | Description | 格式。 


 a| 
` sm_operation_ID_`
 a| 
指定当前操作的 ID
 a| 
string



 a| 
` sm_profile_name_`
 a| 
指定所用配置文件的名称
 a| 
string



 a| 
` sm_host_`
 a| 
指定数据库的主机名
 a| 
string



 a| 
` sm_os_user__`
 a| 
指定数据库的操作系统（ OS ）所有者
 a| 
string



 a| 
` sm_os_Group_`
 a| 
指定数据库的操作系统组
 a| 
string



 a| 
` sm_backup_type_`
 a| 
指定备份的类型（联机，脱机或自动）
 a| 
string



 a| 
` sm_backup_label`
 a| 
指定备份标签
 a| 
string



 a| 
` sm_backup_ID_`
 a| 
指定备份 ID
 a| 
string



 a| 
` sm_backup_profile_s`
 a| 
指定用于备份的配置文件
 a| 
string



 a| 
` sm_recovery_type_`
 a| 
指定恢复配置信息
 a| 
string



 a| 
` sm_volume_restore_mode_`
 a| 
指定卷还原配置
 a| 
string



 a| 
` sm_target_filer_name_`
 a| 
指定目标存储系统名称

[NOTE]
====
如果使用多个存储系统、则存储系统名称必须用逗号分隔。

==== a| 
string



 a| 
` sm_target_volume_name_`
 a| 
指定目标卷名称

[NOTE]
====
目标卷名称必须以存储设备名称作为前缀、例如sm_target_filer_name/sm_target_volume_name。

==== a| 
string



 a| 
` sm_host_file_system_`
 a| 
指定主机文件系统
 a| 
string



 a| 
` sm_snapshot_names_`
 a| 
指定Snapshot列表

[NOTE]
====
Snapshot副本的名称必须以存储系统名称和卷名称作为前缀。Snapshot 副本的名称以逗号分隔。

==== a| 
string array



 a| 
` sm_archive_logs_directory_`
 a| 
指定归档日志目录

[NOTE]
====
如果归档日志位于多个目录中、则这些目录的名称将以逗号分隔。

==== a| 
string array



 a| 
` sm_redo _logs_directory_`
 a| 
指定重做日志目录

[NOTE]
====
如果重做日志位于多个目录中、则这些目录的名称将以逗号分隔。

==== a| 
string array



 a| 
` sm_control_files_directory_`
 a| 
指定控制文件目录

[NOTE]
====
如果控制文件位于多个目录中、则这些目录的名称将以逗号分隔。

==== a| 
string array



 a| 
` sm_data_files_directory_`
 a| 
指定数据文件目录

[NOTE]
====
如果数据文件位于多个目录中、则这些目录的名称将以逗号分隔。

==== a| 
string array

|===