---
permalink: windows/concept-dump-files.html 
sidebar: sidebar 
keywords: dump, file, compress, log, contain, information, snapmanager, environment, operation, profile, system 
summary: 转储文件是一个压缩日志文件，其中包含有关 SnapManager 及其环境的信息。创建的不同类型的日志文件包括操作，配置文件和系统转储文件。 
---
= 转储文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
转储文件是一个压缩日志文件，其中包含有关 SnapManager 及其环境的信息。创建的不同类型的日志文件包括操作，配置文件和系统转储文件。

您可以使用 dump 命令或图形用户界面（ GUI ）中的 * 创建诊断 * 选项卡来收集有关操作，配置文件或环境的信息。系统转储不需要配置文件；但是，配置文件和操作转储需要配置文件。

SnapManager 在转储文件中包含以下诊断信息：

* 已执行的步骤
* 每个步骤完成的时间长度
* 每个步骤的结果
* 操作期间发生的错误（如果有）



NOTE: SnapManager 日志文件或转储文件仅为 root 用户和属于 root 用户组的其他用户启用读写权限。

SnapManager 还在文件中包含以下信息：

* 操作系统版本和架构
* 环境变量
* Java 版本
* SnapManager 版本和架构
* SnapManager 首选项
* SnapManager 消息
* log4j 属性
* SnapDrive 版本和架构
* SnapDrive 日志文件
* Oracle 版本
* Oracle OPatch 本地清单详细信息
* 存储库数据库 Oracle 版本
* 目标数据库类型（独立）
* 目标数据库角色（主数据库，物理备用数据库或逻辑备用数据库）
* 目标数据库 Oracle Recovery Manager （ RMAN ）设置（无 RMAN 集成，具有控制文件的 RMAN 或具有目录文件的 RMAN ）
* 目标数据库 Oracle 版本
* 目标数据库的系统标识符（ SID ）
* 存储库数据库服务名称
* 主机上安装的数据库实例
* 配置文件描述符
* 共享内存最大值
* 交换空间信息
* 内存信息
* 多路径环境
* Host Utilities 版本
* 适用于 Windows 的 Microsoft Internet 小型计算机系统接口（ iSCSI ）软件启动程序版本
* BACKINT接口版本
* BR工具版本
* 修补程序级别
* `ssystem verify`命令的输出


转储文件还列出了 Windows 上的 SnapManager 限制。

SnapManager 转储文件还包含 SnapDrive 数据收集器文件和 Oracle 警报日志文件。您可以使用`smsap operation dump`和`smsap profile dump`命令收集Oracle警报日志文件。


NOTE: 系统转储不包含 Oracle 警报日志；但是，配置文件和操作转储包含警报日志。

即使 SnapManager 主机服务器未运行，您也可以使用命令行界面（ CLI ）或 GUI 访问转储信息。

如果遇到无法解决的问题，您可以将这些文件发送到 NetApp 全球服务。
