---
permalink: windows/reference-the-smosmsapcredential-set-command.html 
sidebar: sidebar 
keywords: command, credential, user, access, secure, resource, host, repository, repositories, database, profile, password, snapmanager, option, smsap 
summary: 此命令可用于为用户设置凭据，以访问主机，存储库和数据库配置文件等安全资源。主机密码是运行 SnapManager 的主机上的用户密码。存储库密码是包含 SnapManager 存储库模式的 Oracle 用户的密码。配置文件密码是由创建配置文件的人员创建的密码。对于主机和存储库选项，如果不包含可选的 -password 选项，系统将提示您输入命令参数中指定的类型的密码。 
---
= smsap credential set命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此命令可用于为用户设置凭据，以访问主机，存储库和数据库配置文件等安全资源。主机密码是运行 SnapManager 的主机上的用户密码。存储库密码是包含 SnapManager 存储库模式的 Oracle 用户的密码。配置文件密码是由创建配置文件的人员创建的密码。对于主机和存储库选项、如果不包含可选的`-password`选项、则系统将提示您输入命令参数中指定类型的密码。



== 语法

[listing]
----

smsap credential set
[-host
-name host_name
-username username]
[-password password]] |
[-repository
-dbname repo_service_name
-host repo_host
-login -username repo_username] [-password repo_password]]
-port repo_port |
[-profile
-name profile_name]
[-password password]]
[-quiet | -verbose]
----


== Parameters

* *`主机_hostname_`*
+
指定运行 SnapManager 的主机服务器的名称或 IP 地址。

+
`-host`参数包括以下选项：

+
** `名称host_name`：指定要为其设置密码的主机的名称。
** `用户名user_name`：指定主机上的用户名。
** `密码密码`：指定主机上用户的密码。


* *`-repository -dbname`*
+
指定存储配置文件的数据库的名称。使用全局名称或 SID 。

+
` repository`参数包括以下选项：

+
** `-dbnamerepo_service_name`：指定存储配置文件的数据库的名称。使用全局名称或 SID 。
** `主机repo_host`：指定运行存储库数据库的主机服务器的名称或IP地址。
** `-login-username repo_username`：指定访问存储库的数据库所需的用户名。
** `密码密码`：指定访问存储库的数据库所需的密码。
** `端口repo_port`：指定用于访问存储库的数据库的TCP端口号。


* *`配置文件-name _profile_name_`*
+
指定与数据库关联的配置文件。

+
`配置文件`参数包括以下选项：

+
** `名称profilename`：指定要为其设置密码的配置文件的名称。
** `密码密码`：指定访问配置文件所需的密码。


* *`-静默`*
+
在控制台上仅显示错误消息。默认情况下会显示错误和警告消息。

* *`-详细`*
+
在控制台上显示错误，警告和信息性消息。





== 用于设置存储库凭据的命令示例

以下示例将设置存储库的凭据。

[listing]
----

smsap credential set -repository -dbname SMSAPREPO -host hotspur -port 1527 -login -username chris
Password for chris@hotspur:1527/SMSAPREPO : ********
Confirm password for chris@hotspur:1527/SMSAPREPO : ********
----
[listing]
----
SMSAP-12345 [INFO ]: Updating credential cache for OS user "admin1"
SMSAP-12345 [INFO ]: Set repository credential for user "user1" on repo1@Host2.
Operation Id [Nff8080810da9018f010da901a0170001] succeeded.
----


== 用于设置主机凭据的命令示例

由于主机凭据表示实际的操作系统凭据，因此，除了密码之外，还必须包含用户名。

[listing]
----
smsap credential set -host -name bismarck -username avida
Password for avida@bismarck : ********
Confirm password for avida@bismarck : ********
----