---
permalink: windows/reference-the-smosmsapbackup-restore-command.html 
sidebar: sidebar 
keywords: run, backup, restore, command, database, portion, information, smsap 
summary: 您可以运行 backup restore 命令来还原数据库或数据库的一部分的备份，然后可以选择恢复数据库信息。 
---
= smsap backup restore命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以运行`backup restore`命令来还原数据库或部分数据库的备份、然后可以选择恢复数据库信息。



== 语法

[listing]
----

smsap backup restore
-profile profile_name
[-label label | -id id]
[-files files [files...] |
-tablespaces tablespaces [tablespaces...]] |
-complete | -controlfiles]
[-recover {-alllogs | -nologs | -until until} [-using-backup-controlfile]]
[-restorespec restorespec | ]]
[-preview]

[-recover-from-location path1 [, path2]]
[-taskspec taskspec]
[-dump]
[-force]
[-quiet | -verbose]
----


== Parameters

* *`配置文件_profile_name_`*
+
指定要还原的数据库。配置文件包含数据库的标识符和其他数据库信息。

* *`-label _name_`*
+
使用指定标签还原备份。

* *`-id _guid_`*
+
使用指定 GUID 还原备份。GUID 由 SnapManager 在创建备份时生成。您可以使用`smsap backup list`命令显示每个备份的GUID。

* *`选择全部或指定文件`*
+
您也可以选择使用以下选项之一：

+
** `完整`：还原备份中的所有数据文件。
** `表空间list`：仅从备份还原指定的表空间。
+
必须使用空格分隔列表中的名称。

** `文件列表`：仅从备份还原指定的数据文件。
+
必须使用空格分隔列表中的名称。如果数据库正在运行，则 SnapManager 可确保包含文件的表空间处于脱机状态。



* *`-controlfiles`*
+
还原控制文件。使用 SnapManager ，您可以通过一次操作从备份中还原控制文件以及数据文件。`-controlfiles`选项与其他还原范围参数无关、例如`-complete`、`-tablespaces`和`-files`。

* *`恢复`*
+
还原数据库后恢复数据库。您还必须使用以下选项之一指定希望 SnapManager 将数据库恢复到的点：

+
** ` nologs`：将数据库恢复到备份时间、不应用任何日志。
+
您可以将此参数用于联机或脱机备份。

** `-alllogs`：将数据库恢复到最后一个事务或提交、并应用所有必需的日志。
** `-直到日期`：将数据库恢复到指定的日期和时间。
+
您必须使用年-月-日：小时：分钟：秒(_yyyy-mm-dd：hh：mm：ss_)格式。对于小时，请根据数据库设置使用 12 小时或 24 小时格式。

** `-直到SCN`：前滚数据文件、直到达到指定的系统更改号(SCN)。
** `使用备份控制文件`：使用备份控制文件恢复数据库。


* *`-restorSpec`*
+
用于将数据还原到活动文件系统，并通过提供每个原始 Snapshot 副本到其活动文件系统的映射从指定数据进行还原。如果未指定选项， SnapManager 将从主存储上的 Snapshot 副本还原数据。您可以指定以下选项之一：

+
** `-restorspecies`：指定要还原的数据和还原格式。


* *`预览`*
+
显示以下信息：

+
** 将使用哪个还原机制（存储端文件系统还原，存储端文件还原或主机端文件副本还原）来还原每个文件
** 为什么不使用更高效的机制来还原每个文件、指定`详细`选项时如果使用的是`预览`选项、则必须了解以下信息：
** `-force`选项不会影响命令。
** `-recover`选项不会影响命令。要预览还原操作，必须挂载数据库。如果要预览还原计划，并且当前未挂载数据库，则 SnapManager 会挂载数据库。如果无法挂载数据库，则此命令将失败， SnapManager 会将数据库返回到其原始状态。


+
`预览`选项最多可显示20个文件。您可以配置要在`smsap.config文件`中显示的最大文件数。

* *`恢复位置`*
+
指定归档日志文件的外部归档日志位置。SnapManager 会从外部位置获取归档日志文件，并使用这些文件进行恢复过程。

* *`任务规范`*
+
指定还原操作的预处理活动或后处理活动的任务规范 XML 文件。您必须提供任务规范 XML 文件的完整路径。

* *`转储`*
+
指定在还原操作后收集转储文件。

* *`强制`*
+
如有必要，将数据库状态更改为低于其当前状态。

+
默认情况下， SnapManager 可以在操作期间将数据库状态更改为更高的状态。要使 SnapManager 将数据库更改为更高状态，不需要此选项。

* *`-静默`*
+
在控制台中仅显示错误消息。默认设置为显示错误和警告消息。

* *`-详细`*
+
在控制台中显示错误，警告和信息性消息。您可以使用此选项来了解为何无法使用效率更高的还原进程来还原文件。





== 示例

以下示例将还原数据库以及控制文件：

[listing]
----
smsap backup restore -profile SALES1 -label full_backup_sales_May
-complete -controlfiles -force
----