---
permalink: windows/task-clone-databases-from-backups.html 
sidebar: sidebar 
keywords: clone, database, backup, create, command 
summary: 您可以使用 clone create 命令从备份克隆数据库。 
---
= 从备份克隆数据库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用`clone create`命令从备份克隆数据库。



== 关于此任务

您必须先为数据库创建克隆规范文件。SnapManager 将根据此规范文件中的信息创建克隆。

克隆数据库后、您可能需要使用新克隆的数据库连接信息更新客户端计算机上的`tnsnames.ora`文件。使用`tnsnames.ora`文件连接到Oracle实例、而无需指定完整的数据库信息。SnapManager 不会更新`tnsnames.ora`文件。

如果您使用的是使用` include-with -online backups`创建的配置文件、则SnapManager 始终会创建一个包含归档日志文件的备份。使用 SnapManager ，您只能克隆完整的数据库备份。

通过 SnapManager （ 3.2 或更高版本），您可以克隆包含数据文件和归档日志文件的备份。

如果可以从外部位置访问归档日志，则可以在克隆期间指定外部位置，以便将克隆的数据库恢复到一致的状态。您必须确保 Oracle 可访问外部位置。不支持克隆仅归档日志备份。

虽然归档日志备份是与联机部分备份一起创建的，但您不能使用此备份创建数据库克隆。

在指定外部归档日志位置以将克隆的数据库恢复为一致状态时，必须确保将外部位置名称完全包含在大写中。在文件系统中，所有文件夹和子文件夹的名称必须为大写，因为 Oracle 数据库会将目标路径转换为大写，并要求外部目标路径，文件夹名称和子文件夹名称采用大写。如果以小写形式指定外部归档日志目标路径，则数据库可能无法识别指定路径，并且无法恢复克隆的数据库。

您只能从独立数据库的外部归档日志文件位置克隆数据库备份。

您可以将`-dump`选项指定为可选参数、以便在克隆创建操作成功或失败后收集转储文件。

* 克隆数据文件备份而不使用归档日志备份 *

如果数据文件备份不包括归档日志备份、则SnapManager for SAP将根据备份期间记录的系统更改编号(SCN)克隆数据库。如果无法恢复克隆的数据库、则会显示有关完成恢复所需的线程<number>和change <SCN>的`归档日志文件`错误消息、即使SnapManager for SAP继续克隆数据库、并最终成功创建克隆。

使用数据文件备份而不包括归档日志备份进行克隆时， SnapManager 会恢复克隆的数据库，直到备份期间记录的最后一个归档日志 SCN 为止。

.步骤
. 创建克隆规范文件。
. 要创建克隆、请输入以下命令：
+
`+smsap clone create-backup-labelbackup_name-newsidnew_sid-labelclone_label-profileprofileprofile_name-clonesfull_path_to_clonspecfile (-spec_taskspec_）[-recover-from-location] path1 (、<path2>...）] [-dump]+`


