---
permalink: windows/task-updating-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, backup, database, operating, system, authentication, information, host, oracle, updating 
summary: 您可以更新配置文件以修改配置文件密码，要保留的备份数，对数据库的访问，对数据库进行身份验证的操作系统 \ （ OS\ ）身份验证，反之亦然，以及有关主机的信息。如果 Oracle 数据库密码信息发生更改，您还必须在配置文件中更改此信息。 
---
= 正在更新配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更新配置文件以修改配置文件密码，要保留的备份数，对数据库的访问，对数据库进行身份验证的操作系统（ OS ）身份验证（反之亦然）以及有关主机的信息。如果 Oracle 数据库密码信息发生更改，您还必须在配置文件中更改此信息。

通过 SnapManager （ 3.2 或更高版本），您可以使用 -separate -archivelog-backups 选项更新配置文件，以便将归档日志备份与数据文件备份分开。您可以为归档日志备份指定单独的保留期限。通过 SnapManager ，您可以将归档日志备份与联机数据库备份一起使用。您还可以同时创建联机数据文件备份和归档日志备份以进行克隆。创建联机数据文件备份时，系统会立即创建归档日志备份以及数据文件。

.步骤
. 输入以下命令：
+
`smsap profile update -profileprofile [-new-profilenew_profile_name]-profile-passwordprofile_password][-database-dbnamedb_dbname-host db_host [-siddb_sidedb][-login -usernamedb_username-password snap_password-port db_port]][｛-database-dman-try_address1_durations1]-mail-try_try_truny<-mail-file_try_try_trusers-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap]<-snap-snap-snap-man_password-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap-snap`

+
此命令的其他选项如下：

+
【 -force】 【 -noprompt】

+
|===
| 如果您要 ... | 那么 ... 


 a| 
* 更改配置文件中数据库备份的备份保留策略 *
 a| 
指定保留类的保留计数或保留期限，或者同时指定这两者以更改保留策略。持续时间以类的单位为单位（例如，小时表示每小时，天表示每天）。

** -hourly 是每小时保留类，其中的 "-countn] 和保留期限分别为保留计数和保留期限。
** -daily 是每日保留类，其保留计数和保留持续时间分别为 "-countn] 和 -durationm]] 。
** -weekly 是每周保留类，其中，对应的保留计数和保留期限分别为 "-countn] 和 -durationm]] 。
** -monthly 是每月保留类别，其保留计数和保留持续时间分别为 "-countn] 和 -durationm]] 。




 a| 
* 为数据库操作的完成状态启用电子邮件通知 *
 a| 
指定以下选项和变量：

** 使用 -summary-notification ，您可以为存储库数据库下的多个配置文件配置摘要电子邮件通知。
** notification 用于接收有关配置文件数据库操作完成状态的电子邮件通知。
** 通过 -success-emailemailemail_address2 ，您可以在使用新配置文件或现有配置文件成功执行数据库操作后收到电子邮件通知。
** 通过 -failure-emailemailemail_address2 ，您可以收到有关使用新配置文件或现有配置文件执行的数据库操作失败的电子邮件通知。
** -subjectsubject_text 指定创建新配置文件或现有配置文件时电子邮件通知的主题文本。如果未为此存储库配置通知设置、而您尝试使用命令行界面(CLI)配置配置文件或摘要通知、则控制台日志中会记录以下消息：smsap-145777：Notification Settings not configured。
+
如果您已配置通知设置、并且正在尝试使用命令行界面配置摘要通知、而不为存储库启用摘要通知、则控制台日志中会记录以下消息：__**__SMSAP-14575：摘要通知配置不可用于此存储库





 a| 
* 更新配置文件以单独创建归档日志文件的备份 *
 a| 
指定以下选项和变量：

** 使用 -separate-archivelog-backups 可以分别为归档日志文件和数据库文件创建备份。
+
指定此选项后，您可以创建仅数据文件备份或仅归档文件备份。您不能创建完整备份。此外，不能通过分离备份来还原配置文件设置。SnapManager 会根据在仅执行归档日志备份之前创建的备份的保留策略保留这些备份。

** -retain-archivelog-backups 用于设置归档日志备份的保留期限。
+

NOTE: 如果您是首次更新配置文件，则可以使用 -separate -archivelog-backups 选项将归档日志备份与数据文件备份分开；您必须使用 -retain-archivelog-backups 选项提供归档日志备份的保留期限。在稍后更新配置文件时，可以选择设置保留期限。

** -include-with -online 备份指定归档日志备份与数据库备份一起包含。
** -no-include-with -online-backups 指定归档日志文件备份不随数据库备份一起提供。




 a| 
* 更改目标数据库的主机名 *
 a| 
指定 -hostnew_db_host 以更改配置文件的主机名。



 a| 
* 在执行配置文件更新操作后收集转储文件 *
 a| 
指定 -dump 选项。

|===
. 要查看更新后的配置文件、请输入以下命令：smsap profile show


* 相关信息 *

xref:concept-how-to-collect-dump-files.adoc[如何收集转储文件]
