---
permalink: windows/task-customize-e-mail-subject-for-a-new-profile.html 
sidebar: sidebar 
keywords: customize, email, subject, profile, create, cusomtizing 
summary: 您可以在创建新配置文件时为其自定义电子邮件主题。 
---
= 自定义新配置文件的电子邮件主题
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在创建新配置文件时为其自定义电子邮件主题。



== 关于此任务

您可以使用 ｛ profile ｝ _ ｛ operation-name ｝ _ ｛ db-SID ｝ _ ｛ db-host ｝ _ ｛ start-date ｝ _ ｛ end-date ｝ _ ｛ status ｝ 模式自定义电子邮件主题，也可以输入您自己的文本。

|===
| 变量名称 | Description | 示例值 


 a| 
`配置文件`
 a| 
用于数据库操作的配置文件名称
 a| 
程序 1



 a| 
`operation-name`
 a| 
数据库操作名称
 a| 
备份，数据备份，数据和归档日志备份



 a| 
`dB-SID`
 a| 
数据库的 SID
 a| 
数据库 1



 a| 
`dB主机`
 a| 
主机服务器的名称
 a| 
主机 A



 a| 
`s开始日期`
 a| 
数据库操作的开始时间，格式为 mmdd ： hh ： ss yyyy
 a| 
2012 年 4 月 27 日 21 ： 00 ： 45 PST



 a| 
`结束日期`
 a| 
数据库操作的结束时间，格式为 mmdd ： hh ： ss yyyy
 a| 
2012 年 4 月 27 日 21 ： 10 ： 45 PST



 a| 
`s状态`
 a| 
数据库操作状态
 a| 
success

|===
如果未为变量提供任何值、则SnapManager 将显示以下错误消息：`mising value (s)-Subject`。

.步骤
. 输入以下命令：
+
`* smsap profile create -profile _profile_[-profile-password _profile_password_]-repository -dbname _repo_service_name_-host _repo_host_-port _repo_port_-login -username _repo_controllusername_-database -dbname _dbname -host _db_db_db_host_用户名_用户名__用户名__用户名_用户名__用户名__用户名_用户名_用户名__用户名__用户名_用户名_____用户名__用户名_用户名____用户名__用户名_用户名______用户名_用户名___用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名_用户名___ _n_](-duration _m_）](-weekly (-count _n_）(-duration _m_）)(-monthly (-count _n_）(-duration _m_]）)(-comment _comment_]（-snapname -pattern _pattern_）)(-notification (-success)-email email _ject_address2、_address2、_unfail___s1`、_unfail___s_


