---
permalink: unix-administration/concept-what-database-backup-scheduling-is.html 
sidebar: sidebar 
keywords: schedule, update, monitor, backup, database, graphical, user, interface, scheduling 
summary: 您可以使用图形用户界面的计划选项卡计划，更新和监控数据库的备份。 
---
= 什么是数据库备份计划
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用图形用户界面的计划选项卡计划，更新和监控数据库的备份。

下表介绍了一些常见的计划问题：

|===
| 问题 | 问题解答 


 a| 
SnapManager 服务器重新启动时计划的备份会发生什么情况？
 a| 
SnapManager 服务器重新启动时，它会自动重新启动所有计划。但是， SnapManager 不会跟踪任何未命中的情况。



 a| 
如果计划同时在两个数据库上进行两个备份，会发生什么情况？
 a| 
SnapManager 一次启动一个备份操作，然后允许并行运行备份。例如，如果数据库管理员为六个不同数据库配置文件创建了六个每日备份计划，这些计划将在凌晨 1 ： 00 进行，则所有六个备份将并行运行。

如果计划在短时间内在一个数据库配置文件上进行多个备份，则 SnapManager 服务器仅运行保留期限最长的备份操作。

在开始备份操作之前， SnapManager 会首先确定以下内容：

* 在过去 30 分钟内，是否有另一个计划成功为同一配置文件创建了一个保留空间更大的备份？
* 在接下来的 30 分钟内，另一个计划是否会尝试为同一个配置文件创建一个保留时间更长的备份？


如果任一问题的问题解答为 yes ，则 SnapManager 将跳过备份。

例如，数据库管理员可能会为数据库配置文件创建每日，每周和每月计划，所有这些计划都计划在凌晨 1 ： 00 进行备份在计划在凌晨 1 ： 00 同时进行三次备份的某一天， SnapManager 仅根据每月计划运行备份操作。

可以在 SnapManager 属性文件中更改 30 分钟的时间窗口。



 a| 
备份操作在哪个用户下运行？
 a| 
此操作在创建计划的用户下运行。但是，如果您拥有数据库配置文件和主机的有效凭据，则可以将此 ID 更改为您自己的用户 ID 。例如，通过为 Avida Davis 创建的备份计划启动计划备份属性， Stella Morrow 可以在 Perform this operation as user 中选择她的用户 ID 来运行计划的备份。



 a| 
SnapManager 计划程序如何与原生操作系统计划程序交互？
 a| 
在 SnapManager 服务器上，您无法通过操作系统的原生计划程序查看计划的备份。例如，创建计划备份后， cron 中不会显示任何其他条目。



 a| 
如果图形用户界面和服务器中的时钟不同步，会发生什么情况？
 a| 
客户端和服务器上的时钟不同步。因此，您可以计划备份，其中开始时间在客户端上是未来的，而在服务器上是过去的。

对于重复备份，服务器仍会满足此请求。例如，如果服务器从 2008 年 1 月 30 日下午 3 ： 00 开始收到执行每小时备份的请求但当前时间为下午 3 ： 30当天，服务器将在下午 4 ： 00 执行首次备份并继续每小时执行一次备份。

但是，对于一次性备份，服务器将按如下方式处理此请求：

* 如果开始时间在当前服务器时间的最后五分钟内，则 SnapManager 会立即开始备份。
* 如果开始时间超过五分钟，则 SnapManager 不会启动备份。


例如，请考虑以下情形：

* 图形界面主机中的时钟比实际时间晚 3 分钟。
* 客户端上的当前时间为上午 8 ： 58
* 您计划在上午 9 ： 00 进行一次性备份
* 您计划在上午 8 ： 30 进行另一次备份


当服务器收到第一个请求时，服务器上的时间为上午 9 ： 01尽管备份的开始时间已过去，但 SnapManager 会立即执行备份。

当服务器收到第二个请求时，备份的开始时间过去超过五分钟。您将收到一条消息，指出由于开始时间已过去，计划请求失败。

您可以在 SnapManager 属性文件中更改五分钟的时间。



 a| 
删除配置文件时，计划备份配置文件会发生什么情况？
 a| 
删除数据库配置文件后， SnapManager 服务器将删除为该配置文件定义的计划备份。



 a| 
在夏令时或更改 SnapManager 服务器时间期间，计划备份的行为如何？
 a| 
由于夏令时或更改了 SnapManager 服务器时间， SnapManager 备份计划将受到影响。

更改 SnapManager 服务器时间时，请考虑以下含义：

* 触发备份计划后，如果 SnapManager 服务器时间有所减少，则备份计划不会再次触发。
* 如果夏令时在计划开始时间之前开始，则会自动触发备份计划。
* 例如，如果您在美国，则计划在凌晨 4 点进行每小时备份备份时间应每 4 小时进行一次，备份时间为 3 月和 11 月调整夏令时前后几天的凌晨 4 点，上午 8 点，中午 12 点，凌晨 4 点，晚上 8 点和午夜。
* 如果备份计划在凌晨 2 ： 30 进行，请注意以下事项每晚：
+
** 当时钟回退一小时时，由于备份已触发，备份不会再次触发。
** 当时钟向前弹出一小时时，备份会立即触发。如果您在美国，并且希望避免使用此问题描述，则必须计划在凌晨 2 ： 00 以外启动备份到凌晨 3 ： 00interval




|===