---
permalink: unix-administration/concept-fast-restore-eligibility-checks.html 
sidebar: sidebar 
keywords: perform, restore, backup, snapmanager, eligibility, check, fast 
summary: 如果您选择快速还原备份， SnapManager 会首先执行资格检查，以确定是否可以使用快速还原过程。 
---
= 快速恢复资格检查
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您选择快速还原备份， SnapManager 会首先执行资格检查，以确定是否可以使用快速还原过程。

SnapManager 提供以下类型的检查：

* 必填检查：只有在此检查下的所有条件均已通过时， SnapManager 才能执行快速还原过程。
* 可覆盖检查：如果此检查的条件失败，管理员可以覆盖此检查以强制执行快速还原过程。但是，您必须谨慎地覆盖这些检查。


下表列出了您可能会遇到的问题，并指示是否可以覆盖快速还原资格检查：

|===
| 问题描述 | 需要通过 | 详细信息 


 a| 
11gR2 中的 ASM 磁盘组中存在 ACFS ，投票磁盘或 OCR
 a| 
是的。
 a| 
无法执行快速还原。解决方法：无

无法覆盖。



 a| 
只能快速还原使用 SnapManager 3.0 或更高版本创建的备份
 a| 
是的。
 a| 
无法覆盖。



 a| 
只能快速还原使用 SnapDrive for UNIX 4.0 或更高版本创建的 Snapshot 副本
 a| 
是的。
 a| 
无法覆盖。



 a| 
卷是根卷
 a| 
是的。
 a| 
要还原的卷是存储系统上的根卷。解决方法：不要在存储系统上使用根卷。

无法覆盖。



 a| 
卷还原在 Windows 上不可用
 a| 
是的。
 a| 
要还原的卷是存储系统上的根卷。解决方法：无

无法覆盖。



 a| 
已禁用卷还原
 a| 
是的。
 a| 
已禁用卷还原。解决方案：启动还原时，通过选择不同的选项来启用卷还原。在命令行界面中、请勿使用`-fast -off`。

无法覆盖。



 a| 
控制同一卷上的文件和数据文件
 a| 
是的。
 a| 
对于联机备份，控制文件和数据文件不能位于同一个卷上，因为 SnapManager 会为该卷创建两个 Snapshot 副本（其中一个数据文件在热备份模式下保持一致）。 热备份模式完成后，备份控制文件保持一致）。卷还原将还原到第一个 Snapshot 副本，此副本将删除包含备份控制文件的第二个 Snapshot 副本。发生纯数据文件还原时，控制文件将还原为不一致状态， SnapManager 将还原备份控制文件，然后使用 resetlogs 选项打开数据库，这不是所需的行为。

解决方案：将控制文件和数据文件迁移到不共享同一底层卷的单独文件系统。这对检查失败的还原没有帮助，但也有助于将来的备份还原操作。

无法覆盖。



 a| 
归档日志和数据文件不能位于同一个卷上
 a| 
是的。
 a| 
数据库归档日志和数据文件驻留在由同一存储系统卷提供支持的文件系统中。如果执行了卷还原， SnapManager 将无法在还原联机备份后打开数据库，因为在数据库退出热备份模式后写入的归档日志文件不可用。此外，您将无法在归档日志文件中的后续事务之间进行前滚。

解决方案：将归档日志和数据文件迁移到不共享同一底层存储系统卷的单独文件系统。这对检查失败的还原没有帮助，但也有助于将来的备份还原操作。

无法覆盖。



 a| 
联机日志和数据文件不能位于同一个卷上
 a| 
是的。
 a| 
数据库联机重做日志和数据文件驻留在由同一存储系统卷提供支持的文件系统中。如果执行了卷还原，则恢复无法使用联机重做日志，因为这些日志可能已还原。

解决方案：将联机重做日志和数据文件迁移到不共享同一底层存储系统卷的单独文件系统。这对检查失败的还原没有帮助，但也有助于将来的备份还原操作。

无法覆盖。



 a| 
文件系统中不属于还原范围的文件将被还原
 a| 
是的。
 a| 
主机上可见的文件（不包括要还原的文件）存在于卷上的文件系统中。如果执行了快速还原或存储端文件系统还原，则在创建 Snapshot 副本时，主机上可见的文件将还原为其原始内容。如果 SnapManager 发现 20 个或更少文件，则资格检查中会列出这些文件。否则， SnapManager 将显示一条消息，指出您应调查文件系统。

解决方案：将数据库未使用的文件迁移到使用不同卷的其他文件系统。或者，也可以删除这些文件。

如果 SnapManager 无法确定文件用途，则可以覆盖检查失败。如果覆盖此检查，则会还原不在还原范围内的文件。仅当您确定还原文件不会对任何内容产生负面影响时，才覆盖此检查。



 a| 
将还原不属于还原范围的指定卷组中的文件系统
 a| 
否
 a| 
多个文件系统位于同一个卷组中，但并非所有文件系统都请求还原。存储端文件系统还原和快速还原不能用于还原卷组中的各个文件系统，因为卷组使用的 LUN 包含所有文件系统中的数据。要使用快速还原或存储端文件系统还原，必须同时还原卷组中的所有文件系统。如果 SnapManager 发现 20 个或更少文件， SnapManager 会在资格检查中列出这些文件。否则， SnapManager 将显示一条消息，指出您应调查文件系统。

解决方案：将数据库未使用的文件迁移到其他卷组。或者，也可以删除卷组中的文件系统。

可以覆盖。



 a| 
系统会还原不属于还原范围的指定卷组中的主机卷
 a| 
否
 a| 
多个主机卷（逻辑卷）位于同一个卷组中，但并非所有主机卷都请求还原。此检查与卷组中的文件系统类似，除了卷组中的其他主机卷未作为文件系统挂载到主机上之外，不会还原此还原范围内的任何文件系统。解决方法：将数据库使用的主机卷迁移到其他卷组。或者，删除卷组中的其他主机卷。

如果覆盖此检查，则卷组中的所有主机卷都将还原。仅当您确定还原其他主机卷不会对任何内容产生不利影响时，才覆盖此检查。



 a| 
自上次备份以来，文件块区已发生更改
 a| 
是的。
 a| 
无法覆盖。



 a| 
还原卷中不属于还原范围的映射 LUN
 a| 
是的。
 a| 
请求在卷中还原的 LUN 以外的 LUN 当前已映射到主机。无法执行卷还原，因为使用这些 LUN 的其他主机或应用程序将变得不稳定。如果 LUN 名称以下划线和整数索引（例如， _0 或 _1 ）结尾，则这些 LUN 通常是同一卷中其他 LUN 的克隆。可能会挂载数据库的另一个备份，或者存在另一个备份的克隆。

解决方法：将数据库未使用的 LUN 迁移到其他卷。如果映射的 LUN 是克隆，请查找同一数据库或数据库克隆的已挂载备份，然后卸载此备份或删除此克隆。

无法覆盖。



 a| 
卷中不属于还原范围的未映射 LUN 将被还原
 a| 
否
 a| 
卷中存在请求还原的 LUN 以外的 LUN 。这些 LUN 当前未映射到任何主机，因此还原它们不会中断任何活动进程。但是， LUN 可能会暂时取消映射。解决方法：将数据库未使用的 LUN 迁移到其他卷或删除 LUN 。

如果覆盖此检查，则卷还原会将这些 LUN 还原到创建 Snapshot 副本时的状态。如果在创建 Snapshot 副本时 LUN 不存在，则在卷还原后 LUN 将不存在。只有在确定还原 LUN 不会对任何内容产生负面影响时，才会覆盖此检查。



 a| 
还原时，卷的 Snapshot 副本中的 LUN 可能不一致
 a| 
否
 a| 
在创建 Snapshot 副本期间，卷中存在请求 Snapshot 副本的 LUN 以外的 LUN 。这些其他 LUN 可能未处于一致状态。解决方法：将数据库未使用的 LUN 迁移到其他卷或删除 LUN 。这对检查失败的还原过程没有帮助，但也有助于还原在移动或删除 LUN 后所做的后续备份。

如果覆盖此检查，则 LUN 将恢复为创建 Snapshot 副本时的不一致状态。只有在确定还原 LUN 不会对任何内容产生负面影响时，才会覆盖此检查。



 a| 
新 Snapshot 副本具有卷克隆
 a| 
是的。
 a| 
已为在请求还原 Snapshot 副本之后创建的 Snapshot 副本创建克隆。由于卷还原将删除稍后的 Snapshot 副本，并且如果 Snapshot 副本具有克隆，则无法删除该副本，因此无法执行卷还原。解决方法：删除后续 Snapshot 副本的克隆。

无法覆盖。



 a| 
此时将挂载较新的备份
 a| 
是的。
 a| 
在还原备份后所做的备份将挂载。由于卷还原会删除稍后的 Snapshot 副本，因此如果 Snapshot 副本具有克隆，则无法删除该副本，备份挂载操作会创建克隆的存储，并且无法执行卷还原。解决方案：卸载后续备份，或者从挂载备份后创建的备份中还原。

无法覆盖。



 a| 
存在较新备份的克隆
 a| 
是的。
 a| 
还原备份后所做的备份已克隆。由于卷还原会删除稍后的 Snapshot 副本，并且如果 Snapshot 副本具有克隆，则无法删除该副本，因此无法执行卷还原。解决方案：删除较新备份的克隆，或者从包含克隆的备份之后创建的备份中进行还原。

无法覆盖。



 a| 
卷的新 Snapshot 副本丢失
 a| 
否
 a| 
执行卷还原将删除在将卷还原到的 Snapshot 副本之后创建的所有 Snapshot 副本。如果 SnapManager 可以将更高版本的 Snapshot 副本映射回同一配置文件中的 SnapManager 备份，则会显示 " 较新的备份将被释放或删除 " 消息。如果 SnapManager 无法将更高版本的 Snapshot 副本映射回同一配置文件中的 SnapManager 备份，则不会显示此消息。解决方案：从后续备份还原或删除后续 Snapshot 副本。

可以覆盖。



 a| 
较新的备份将被释放或删除
 a| 
否
 a| 
执行卷还原将删除在将卷还原到的 Snapshot 副本之后创建的所有 Snapshot 副本。因此，在还原的备份之后创建的任何备份都会被删除或释放。在以下情况下，稍后的备份将被删除：

* 备份状态不受保护
* `retain .alwaysFreeExpiredBackups` is `* false*` in `smsap.config`


在以下情况下，将释放后续备份：

* 备份状态为 " 受保护 "
* `retain .alwaysFreeExpiredBackups`为true `* false*` in `smsap.config`


解决方案：从后续备份还原，或者释放或删除后续备份。

如果覆盖此检查，则会删除或释放在还原的备份之后创建的备份。



 a| 
卷的 SnapMirror 关系丢失
 a| 
是（如果禁用了 RBAC 或您没有 RBAC 权限）
 a| 
在 SnapMirror 关系中，将卷还原到早于基线 Snapshot 副本的 Snapshot 副本会销毁此关系。解决方案：从关系的基线 Snapshot 副本之后创建的备份还原。或者，手动中断存储关系（然后在还原完成后重新创建此关系并重新建立基线）。

如果已启用 RBAC 且您具有 RBAC 权限，则可以覆盖。



 a| 
如果执行快速还原过程，则卷的 SnapVault 关系将丢失
 a| 
是（如果禁用了 RBAC 或您没有 RBAC 权限）
 a| 
在 SnapVault 关系中，将卷还原到早于基线 Snapshot 副本的 Snapshot 副本会销毁此关系。解决方案：从关系的基线 Snapshot 副本之后创建的备份还原。或者，手动中断存储关系（然后在还原完成后重新创建此关系并重新建立基线）。

如果已启用 RBAC 且您具有 RBAC 权限，则无法覆盖。



 a| 
卷中不属于还原范围的 NFS 文件将被还原
 a| 
否
 a| 
如果执行卷还原，则会还原存储系统卷中不可见的文件，而这些文件在主机上不可见。解决方法：将数据库未使用的文件迁移到其他卷或删除这些文件。

可以覆盖。如果覆盖此检查失败，则会删除这些 LUN 。



 a| 
卷存在 CIFS 共享
 a| 
否
 a| 
要还原的卷具有 CIFS 共享。在卷还原期间，其他主机可能正在访问卷中的文件。解决方案：删除不需要的 CIFS 共享。

可以覆盖。



 a| 
从备用位置还原
 a| 
是的。
 a| 
为还原操作提供了还原规范，用于指定从备用位置还原文件。只能使用主机端复制实用程序从备用位置进行还原。

解决方法：无。

无法覆盖。



 a| 
RAC数据库不支持存储端文件系统还原
 a| 
是的。
 a| 
无法覆盖。

|===