---
permalink: unix-administration/concept-when-can-you-use-fast-restore.html 
sidebar: sidebar 
keywords: rule, apply, fast, restore, achieve, optimal, performance, guidelines 
summary: 使用快速还原实现最佳还原性能时，需要遵循特定规则。在某些情况下，您无法使用快速还原。 
---
= 有关何时可以使用快速还原的准则
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用快速还原实现最佳还原性能时，需要遵循特定规则。在某些情况下，您无法使用快速还原。

要获得最佳还原性能（卷还原或完整磁盘组还原），必须遵循以下规则：

* 只有完整备份的完全还原才有资格进行快速还原。
* 只有数据文件才有资格进行快速还原。
* 数据文件必须是卷中唯一符合快速还原条件的文件。
+
尽管临时数据文件可以驻留在卷中，但控制文件，日志， pfiles 或其他文件必须驻留在与数据文件不同的卷上。您必须设置一个 Oracle 数据库，其中的数据文件与控制文件，归档日志和联机日志文件位于不同的卷上。

* 卷中只能包含一个数据库的数据文件。
* 可以使用多个文件系统，但这些文件系统中的文件只能是一个数据库的数据文件。
* SAP需要略有不同的文件布局。
+
"`常规布局和配置`"部分包含详细信息。

* 如果使用`BRRESTORE`还原数据库、则会在备份实用程序参数文件中使用FAST参数和FAST参数进行快速还原。



NOTE: 要使用快速还原检查先前创建的备份是否可还原、您可以使用`smsap backup restore`命令的`-preview`选项。

在以下情况下，无法使用快速还原过程：

* 进行部分备份时
* 从二级存储备份时，如果备份也位于主存储上
+
您不能使用基于文件或基于卷的还原来还原这些。

* 使用 SnapVault 保护的备份
+
快速还原过程不能用于在上次受保护备份之前创建的备份。但是，您可以对上次受保护备份之后创建的备份使用快速还原过程。例如，请考虑备份 A ， B 和 CB 是使用 SnapVault 传输到二级存储的最后一个备份。您可以快速还原 B 和 C ，但无法快速还原 A ，因为它是在上次受保护备份之前创建的。SnapVault 需要一个基线 SnapVault 来计算时间差，并在下次将备份传输到二级存储时发送到二级存储。最后一个受保护备份充当基线 Snapshot 副本。因此，使用快速还原过程会使 SnapVault 无法识别基线。

* 使用在将卷还原到的 Snapshot 副本之后创建的 Snapshot 副本的 FlexClone 或 LUN 克隆
+
例如，克隆可能是 SnapManager 稍后挂载或克隆的备份的结果。

* 不属于活动 SnapDrive Snapshot 副本的 LUN


您不能对同一备份执行快速还原以及其他类型的还原。例如，如果一个数据卷可以使用快速还原过程进行还原，但另一个数据卷无法进行还原，则使用快速还原过程也不会还原这两个数据卷。在这种情况下，您可以选择基于文件的还原。

此外，您还应考虑以下关于数据库还原的几点：

* SnapManager 从不还原归档日志或重做日志，但会挂载归档日志文件的备份并使用它们进行恢复。
* SnapManager 从不使用卷还原来还原控制文件。
* 如果您要还原控制文件和数据文件， SnapManager 将通过两个步骤执行还原。
+
SnapManager 首先还原控制文件，然后还原数据文件。

* 如果 SnapManager 发现临时文件与标准表空间文件位于同一个卷中，则无需执行问题描述覆盖即可执行卷级还原。
+
卷还原后，此临时表空间将恢复联机。



SnapManager for SAP和BACKINT接口在确定可使用的还原机制时使用相同的逻辑。无论备份是使用SnapManager for SAP还是使用BACKINT接口进行的、也无论还原是通过SnapManager for SAP还是通过BACKINT接口执行的、都可以使用所有还原方法。

* 相关信息 *

http://mysupport.netapp.com/["NetApp 支持站点上的文档： mysupport.netapp.com"]
