---
permalink: unix-administration/concept-configuring-e-mail-notification.html 
sidebar: sidebar 
keywords: snapmanager, enable, email, notification, completion, status, profile-executed, database, operation, configuring, configure 
summary: 通过 SnapManager ，您可以接收有关配置文件执行的数据库操作的完成状态的电子邮件通知。SnapManager 会生成电子邮件，并帮助您根据数据库操作完成状态采取适当的操作。配置电子邮件通知是一个可选参数。 
---
= 配置电子邮件通知
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过 SnapManager ，您可以接收有关配置文件执行的数据库操作的完成状态的电子邮件通知。SnapManager 会生成电子邮件，并帮助您根据数据库操作完成状态采取适当的操作。配置电子邮件通知是一个可选参数。

您可以将单个配置文件的电子邮件通知配置为配置文件通知，并将存储库数据库上的多个配置文件的电子邮件通知配置为摘要通知。

* 配置文件通知 *

对于单个配置文件，您可以收到一封有关数据库操作成功或失败的电子邮件。


NOTE: 默认情况下，数据库操作失败时会启用电子邮件通知。

* 摘要通知 *

通过摘要通知，您可以接收有关使用多个配置文件执行的数据库操作的摘要电子邮件。您可以启用每小时，每天，每周或每月通知。


NOTE: 在 SnapManager 3.3 中，只有在指定了必须发送通知的主机服务器时，才会发送摘要通知。如果从 3.3 之前的版本升级 SnapManager ，则如果未在摘要通知配置中指定主机服务器，则可能不会发送摘要通知。


NOTE: 如果在 Real Application Clusters （ RAC ）环境中数据库的一个节点中创建存储库并启用摘要通知，则稍后在将同一存储库添加到数据库的另一个节点时，系统会发送两次摘要通知电子邮件。

您可以一次使用配置文件级别的通知或摘要通知。

SnapManager 为以下配置文件执行的数据库操作启用电子邮件通知：

* 在主存储上创建备份
* 还原备份
* 创建克隆
* 拆分克隆
* 验证备份


在启用了电子邮件通知的情况下创建或更新配置文件后，您可以将其禁用。如果禁用电子邮件通知，则不再收到这些配置文件执行的数据库操作的电子邮件警报。

您收到的电子邮件包含以下详细信息：

* 数据库操作的名称，例如备份，还原或克隆
* 用于数据库操作的配置文件名称
* 主机服务器的名称
* 数据库的系统标识符
* 数据库操作的开始和结束时间
* 数据库操作的状态
* 错误消息（如果有）
* 警告消息（如果有）


您可以配置以下内容：

* 存储库的邮件服务器
* 新配置文件的电子邮件通知
* 现有配置文件的电子邮件通知
* 存储库下多个配置文件的摘要电子邮件通知



NOTE: 您可以从命令行界面（ CLI ）和图形用户界面（ GUI ）配置电子邮件通知。
