---
permalink: unix-administration/concept-what-database-restore-is.html 
sidebar: sidebar 
keywords: snapmanager, enable, volume-based, file-based, backup, restore, operation, database, restore 
summary: 通过 SnapManager ，您可以执行基于卷或基于文件的备份和还原操作。 
---
= 什么是数据库还原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用SnapManager 可以执行基于卷或基于文件的备份和还原操作。

下表介绍了还原方法：

[cols="1a,3a"]
|===
| 还原过程 | 详细信息 


 a| 
基于卷的快速恢复（从主存储）
 a| 
SnapManager 通过还原完整卷来还原数据库的数据文件。此默认过程是还原数据库的最快方法。



 a| 
基于文件的还原
 a| 
存储端完整文件系统还原（从主系统或二级系统）： SnapManager 执行完整逻辑单元号（ LUN ）还原。



 a| 
存储端文件还原：SnapManager 在NAS环境中执行单个文件快照还原(SFSR)。在SFSR中、代表受保护对象的每个文件或LUN都会进行还原。



 a| 
主机端文件副本还原（从主卷或二级卷）： SnapManager 使用 LUN 或 FlexClone 克隆本地备份。此时将挂载克隆，然后 SnapManager 会将主机文件从克隆复制到活动文件系统。

|===

NOTE: 如果主存储上也存在备份，则无法从二级存储还原备份。

快速还原操作完成后， SnapManager 将执行以下任务：

* 释放同一配置文件中较新的备份（在还原备份后进行），因为它们的 Snapshot 副本不再位于主存储上。
* 删除同一配置文件中所有 Snapshot 副本的备份，这些备份会通过快速还原过程自动删除任何 Snapshot 副本。
+
这样可以防止备份被部分释放。例如， Backup_A 是先创建的，而 Backup_B 是先创建的。每个文件都有一个 Snapshot 副本用于数据文件，一个用于归档日志。在 SnapManager 使用快速还原过程还原 Backup_A 之后， SnapManager 会自动从 Backup_B 中删除数据文件 Snapshot 副本由于未在快速还原过程中还原归档日志，因此在快速还原过程完成后， SnapManager 必须删除此归档日志的 Backup_B Snapshot 副本。





== 快速还原

快速还原或基于卷的还原之所以命名为，是因为它是最快的还原方法。整个存储系统卷将还原为 Snapshot 副本。在存储级别，此还原几乎是瞬时的。但是，执行卷还原可能会产生以下负面影响，因此必须谨慎使用：

* 还原整个存储端卷，包括以下内容：
+
** 不视为备份一部分的文件
** 卷上的其他文件，文件系统或 LUN


* 删除在将卷还原到的 Snapshot 副本之后创建的所有 Snapshot 副本。
+
例如，如果卷还原了星期一的备份，则无法再还原星期二的备份。

* 如果还原的 Snapshot 副本早于此关系中的基线 Snapshot 副本，则与二级存储系统的关系将中断。




== 存储端完整文件系统还原

如果无法执行卷还原，但可以在存储系统上还原整个文件系统，则会执行存储端完整文件系统还原。

执行存储端文件系统还原时，将发生以下情况：

* 在 SAN 环境中，文件系统使用的所有 LUN （以及底层卷组（如果有）都会还原到存储系统上。
* 在 NAS 环境中，文件系统中的每个文件都会在存储系统上还原。
+
对于 NAS 环境，与存储端文件还原相比，此还原机制不会提供额外的优势。



执行存储端文件系统还原时，根据存储位置，将发生以下情况：

* 从主存储系统还原 SnapManager 时， LUN （ SAN ）或文件（ NAS ）将通过 SFSR 原位还原。
* 从二级存储系统还原 SnapManager 时， LUN （ SAN ）或文件（ NAS ）会通过网络从二级存储系统复制回主存储系统。


由于文件系统已完全还原，因此也会还原不属于备份的文件。如果要还原的文件系统中存在非还原过程中的文件，则需要覆盖。



== 存储端文件还原

有时，如果无法执行存储端文件系统还原，则会执行存储端文件还原。在存储端文件还原中，文件系统中的各个文件将直接在存储系统上还原。

此类还原只能在NFS环境中执行、或者在某些情况下可以在ASM环境中执行。

执行存储端文件还原时，将发生以下情况：

* 当 SnapManager 从主存储系统还原 NFS 文件时，各个文件将使用 SFSR 原位还原。
* 当 SnapManager 从二级存储系统还原 NFS 文件时，各个文件将通过存储网络复制回主存储系统。




== 主机端文件还原

如果无法执行快速还原，存储端文件系统还原和存储端文件还原，则在 SAN 环境中，主机端文件副本还原是最后一种选择。

主机端文件副本还原涉及以下任务：

* 克隆存储
* 将克隆的存储连接到主机
* 将文件从克隆文件系统复制回活动文件系统
* 断开克隆存储与主机的连接
* 删除克隆存储


从二级存储还原时， SnapManager 会首先尝试将数据直接从二级存储系统还原到主存储系统（而不涉及主机）。如果 SnapManager 无法执行此类还原（例如，如果文件系统中存在不属于还原的文件），则 SnapManager 将执行主机端文件副本还原。SnapManager 可通过两种方法从二级存储执行主机端文件副本还原。SnapManager 选择的方法在`smsap.config`文件中进行配置。

* Direct ： SnapManager 克隆二级存储上的数据，将克隆的数据从二级存储系统挂载到主机，然后将数据从克隆复制到活动环境。这是默认的二级访问策略。
* 间接： SnapManager 首先将数据复制到主存储上的临时卷，然后将数据从临时卷挂载到主机，然后将数据从临时卷复制到活动环境。只有当主机无法直接访问二级存储系统时，才应使用此二级访问策略。使用此方法进行恢复所需时间是直接二级访问策略的两倍，因为会创建两个数据副本。


是否使用直接或间接方法取决于`smsap.config`配置文件中的`restore.secondaryAccessPolicy`参数值。默认值为 DIRECT 。
