---
permalink: unix-administration/concept-managing-security-and-credentials.html 
sidebar: sidebar 
keywords: manage, security, snapmanager, apply, authentication, role-base, access, control, rbac, credential, management 
summary: 您可以通过应用用户身份验证和基于角色的访问控制（ RBAC ）来管理 SnapManager 中的安全性。通过用户身份验证方法，您可以访问存储库，主机和配置文件等资源。使用 RBAC ，您可以限制 SnapManager 对数据库中包含数据文件的卷和 LUN 执行的操作。 
---
= 安全性和凭据管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过应用用户身份验证和基于角色的访问控制（ RBAC ）来管理 SnapManager 中的安全性。通过用户身份验证方法，您可以访问存储库，主机和配置文件等资源。使用 RBAC ，您可以限制 SnapManager 对数据库中包含数据文件的卷和 LUN 执行的操作。

使用命令行界面（ CLI ）或图形用户界面（ GUI ）执行操作时， SnapManager 会检索为存储库和配置文件设置的凭据。SnapManager 会保存先前安装的凭据。

可以使用密码保护存储库和配置文件。凭据是为用户配置的对象密码，而不是在对象本身上配置密码。

您可以通过执行以下任务来管理身份验证和凭据：

* 通过操作时的密码提示或使用`smsap credential set`命令来管理用户身份验证。
+
设置存储库，主机或配置文件的凭据。

* 查看用于管理您有权访问的资源的凭据。
* 清除所有资源（主机，存储库和配置文件）的用户凭据。
* 删除单个资源（主机，存储库和配置文件）的用户凭据。


您可以通过执行以下任务来管理基于角色的访问：

* 使用 SnapDrive 为 SnapManager 启用 RBAC 。
* 使用 Operations Manager 控制台为用户分配角色并设置角色功能。
* 也可以通过编辑`smsap.config文件`来启用SnapManager 以存储加密密码。


如果安装了 Protection Manager ，则对功能的访问将通过以下方式受到影响：

* 如果安装了 Protection Manager ，则在创建数据库配置文件时， SnapManager 会创建一个数据集，并使用包含数据库文件的卷填充此数据集。
+
执行备份操作后， SnapManager 会使数据集内容与数据库文件保持同步。

* 如果未安装 Protection Manager ，则 SnapManager 无法创建数据集，并且您无法对配置文件设置保护。

