---
permalink: unix-administration/reference-error-messages.html 
sidebar: sidebar 
keywords: information, error, message, associate, snapmanager, operation 
summary: 您可以找到有关与不同 SnapManager 操作关联的错误消息的信息。 
---
= 错误消息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以找到有关与不同 SnapManager 操作关联的错误消息的信息。



== 最常见的错误消息

下表列出了与SnapManager for SAP关联的一些最常见且最重要的错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sD-10038：文件系统不可写。`
 a| 
SnapManager 进程不具有对文件系统的写入访问权限。
 a| 
您必须确保 SnapManager 进程对文件系统具有写入访问权限。更正此错误后，您可能需要创建另一个快照。



 a| 
`sMSAP-05075：无法创建配置文件。您必须正确配置DP/XDP关系、或者根据底层关系选择正确的保护策略。`
 a| 
底层卷不处于 SnapVault 或 SnapMirror 关系中。
 a| 
您必须在源卷和目标卷之间配置数据保护关系并初始化此关系。



 a| 
` smsap-05550]您已为此配置文件指定相同的名称。指定其他名称以重命名配置文件。`
 a| 
名称相同的配置文件不能位于存储库中。
 a| 
请提供未使用的配置文件名称。



 a| 
`sMSAP-05505：无法更新数据集元数据。`
 a| 
数据集可能已删除或不存在。
 a| 
在更新数据集元数据之前，请使用 NetApp 管理控制台验证数据集是否存在。



 a| 
`sMSAP-05506：您无法更新此配置文件、因为此配置文件正在运行操作。您必须等待操作完成、然后更新配置文件`
 a| 
执行备份，还原和克隆操作时，无法更新配置文件。
 a| 
完成当前操作后更新配置文件。



 a| 
`sMSAP-05509：archivelog主保留期限无效-指定正整数值。`
 a| 
归档日志备份的保留期限不能为负数。
 a| 
为归档日志备份的保留期限指定一个正值。



 a| 
`sMSAP-07466：此备份还原要求数据库处于所需状态。无法将数据库置于所需状态。`
 a| 
数据库未处于备份操作所需的状态。
 a| 
在创建备份副本之前，请检查数据库是否处于相关状态。要还原的数据库的状态取决于要执行的还原过程的类型以及要包含的文件类型。



 a| 
`sMSAP-09315：执行存储库升级或更新操作后、除非使用通知主机详细信息更新摘要通知、否则您可能无法收到在先前版本中设置的通知的摘要通知。`
 a| 
滚动升级后，系统不会为此存储库配置通知设置。
 a| 
滚动升级后，更新摘要通知设置以接收通知。



 a| 
`sMSAP-02076：标签名称不应包含除下划线以外的任何特殊字符。`
 a| 
标签名称包含除下划线以外的其他特殊字符。
 a| 
标签名称在配置文件中必须是唯一的。此名称可以包含字母，数字，下划线（ _ ）和连字符（ - ）（但不能以连字符开头）。确保标签不包含除下划线以外的任何特殊字符。



 a| 
`sMSAP-06308：尝试启动计划时出现异常：java.lang.NullPointerException`
 a| 
配置配置文件主机的完全限定域名（ FQDN ）而不是系统的主机名，并且无法解析配置文件主机的 FQDN 。
 a| 
请确保使用系统的主机名，而不是 FQDN 。



 a| 
`ExecuteRestoreSteps中的故障：ORACLE-10003：针对Oracle数据库+ASM1执行SQL "drop diskgroup；control diskgroup name；including contents"时出错：ora-15039：diskgroup not dropped ORA-15027：active use of diskgroup；"control diskgroup name；" precludes its dismount`
 a| 
使用控制文件还原备份的操作无法删除控制磁盘组。如果控制磁盘组中备份的控制文件已过时，则会发生此问题描述。
 a| 
确定已备份的陈旧控制文件并手动将其删除。



 a| 
`RMAN-06004：恢复目录数据库中的Oracle错误：ora-01424：转义字符`后面缺少字符或字符非法
 a| 
如果 SnapManager 与 RMAN 集成，则备份创建操作无法从目录中删除备份副本。
 a| 
检查是否存在用于从 RMAN 删除备份的外部脚本。在RMAN中执行`* Crosscheck backup*`命令以更新RMAN存储库、并使用`* resync catalog *`命令将目标数据库的控制文件与恢复目录同步。



 a| 
`调试：删减备份时出现异常。java.lang.IllegalStateException：[Assertion failed]-此状态不变必须为true`
 a| 
系统会为一个操作 ID 创建多个 Snapshot 副本。
 a| 
手动删除 Snapshot 副本并使用脚本从存储库中删除条目。



 a| 
SnapManager 在日志文件中显示的系统时间和时间不匹配或不同步。
 a| 
Java 7 尚不支持更改时区。
 a| 
应用Oracle提供的`tzupdateer`修补程序。



 a| 
`dISC-001：无法发现存储：以下标识符不存在或不是预期类型：ASM File`
 a| 
数据或控制文件或重做日志会在 ASM 数据库中进行多路传输。
 a| 
删除 Oracle 多路复用。



 a| 
`0001-DS-10021：无法将数据集<datase-name>的保护策略设置为<new-protection-policy>、因为保护策略已设置为<old-protection-policy>。请使用Protection Manager更改保护策略`
 a| 
设置数据集的保护策略后， SnapManager 将不允许您更改保护策略，因为它可能需要重新对基线关系进行对齐，并导致二级存储上的现有备份丢失。
 a| 
使用 Protection Manager 的管理控制台更新保护策略，该控制台提供了有关从一个保护策略迁移到另一个保护策略的更多选项。



 a| 
`0001-SD-10028：SnapDrive 错误(ID：2618代码：102)无法发现与"LUN_path"关联的设备。如果正在使用多路径，可能会出现多路径配置错误。请验证配置并重试。`
 a| 
主机无法发现在存储系统上创建的 LUN 。
 a| 
确保传输协议已正确安装和配置。确保 SnapDrive 可以在存储系统上创建和发现 LUN 。



 a| 
`0001-SD-10028：SnapDrive 错误(ID：2836代码：110)无法获取卷"storage name"："temp_volume_name"`上的数据集锁定
 a| 
您尝试使用间接存储方法进行还原，但指定的临时卷不在主存储上。
 a| 
在主存储上创建临时卷。或者，如果已创建临时卷，请指定正确的卷名称。



 a| 
`0001-smsap-02016：在此备份操作中、数据库中可能存在未备份的外部表(因为在此备份期间数据库未打开、因此无法查询all_external_locations以确定是否存在外部表)。`
 a| 
SnapManager 不会备份外部表（例如，不存储在 .dbf 文件中的表）。之所以出现此问题描述，是因为备份期间未打开数据库， SnapManager 无法确定是否正在使用任何外部表。
 a| 
在此操作中，数据库中可能存在未备份的外部表（因为数据库在备份期间未打开）。



 a| 
`0001-smsap-11027：由于快照繁忙、无法从二级存储克隆或挂载快照。尝试从旧备份克隆或挂载。`
 a| 
您尝试从最新受保护备份的二级存储创建克隆或挂载 Snapshot 副本。
 a| 
从较早的备份克隆或挂载。



 a| 
`0001-smsap-12346：无法列出保护策略、因为未安装Protection Manager产品或未将SnapDrive 配置为使用它。请安装保护管理器和/或配置SnapDrive ...`
 a| 
您尝试在未将 SnapDrive 配置为使用 Protection Manager 的系统上列出保护策略。
 a| 
安装 Protection Manager 并配置 SnapDrive 以使用 Protection Manager 。



 a| 
`0001-smsap-13032：无法执行操作：备份删除。根发生原因 ：0001-smsap-02039：无法删除数据集备份：SD-10028：SnapDrive 错误(ID：2406代码：102)无法删除备份ID：数据集的"backup_id"、错误(23410)：卷"volume_name"上的Snapshot"snapshot_name" is busy。`
 a| 
您已尝试释放或删除最新受保护的备份或包含镜像关系中基线 Snapshot 副本的备份。
 a| 
释放或删除受保护的备份。



 a| 
`0002-332管理员错误：无法检查对卷"volume_name"的sd.snapshot.Clone访问权限、以查找Operations Manager服务器"DFM_server"上的用户用户名。原因：指定的资源无效。在Operations Manager服务器"DFM_server"`上找不到其ID
 a| 
未设置正确的访问权限和角色。
 a| 
为尝试执行命令的用户设置访问权限或角色。



 a| 
``、warning] flow-11011：操作中止了[错误] flow-11-8：操作失败：java堆空间。
 a| 
数据库中的归档日志文件数量超过允许的最大数量。
 a| 
. 导航到 SnapManager 安装目录。
. 打开`launch -java`文件。
. 增加 `java -Xmx160m` java heap space 参数的值。例如，您可以将此值从默认值 160 米修改为 200 米，并将其修改为 `java -Xmx200 米` 。




 a| 
`sD-10028：SnapDrive 错误(ID：2868代码：102)找不到远程快照或远程qtree。`
 a| 
即使 Protection Manager 中的保护作业仅部分成功， SnapManager 也会将备份显示为受保护。在数据集遵从性正在进行中时（在镜像基线快照时），会发生此情况。
 a| 
在数据集符合要求后进行新备份。



 a| 
`sMSAP-21019：对目标："/mnt/destination_name/"执行归档日志删减失败、原因："ORACLE-00101：执行RMAN命令时出错：[delete NOPROMPT ARCHIVELOG"/mnt/destination_name/"]`
 a| 
在其中一个目标中，归档日志修剪失败。在这种情况下， SnapManager 会继续从其他目标对归档日志文件进行修剪。如果从活动文件系统手动删除任何文件， RMAN 将无法从该目标对归档日志文件进行修剪。
 a| 
从 SnapManager 主机连接到 RMAN 。运行RMAN `* Crosscheck ARCHIVELOG all*`命令、然后对归档日志文件再次执行修剪操作。



 a| 
`sMSAP-13032：无法执行操作：归档日志Prune.根发生原因 ：RMAN异常：ORACLE-00101：执行RMAN命令时出错。`
 a| 
归档日志文件将从归档日志目标位置手动删除。
 a| 
从 SnapManager 主机连接到 RMAN 。运行RMAN `* Crosscheck ARCHIVELOG all*`命令、然后对归档日志文件再次执行修剪操作。



 a| 
`无法解析Shell输出：(java.util.regex.Matcher[pattern=Command complete。Region = 0、18 lastmatch=])不匹配(名称：backup_script)`

`无法解析Shell输出：(java.util.regex.Matcher[pattern=Command complete。Region = 0、25 lastmatch=])不匹配(说明：备份脚本)`

`无法解析Shell输出：(java.util.regex.Matcher[pattern=Command complete。Region = 0.9 lastmatch=])不匹配(超时：0)`
 a| 
未在任务前或任务后脚本中正确设置环境变量。
 a| 
检查任务前或任务后脚本是否遵循标准 SnapManager 插件结构。有关追加信息在脚本中使用环境变量的信息，请参见 xref:concept-operations-in-task-scripts.adoc[任务脚本中的操作]。



 a| 
`ORA-01450：已超过最大密钥长度(6398)。`
 a| 
在从适用于SAP的SnapManager 3.2升级到适用于SAP的SnapManager 3.3时、升级操作将失败并显示此错误消息。之所以出现此问题描述，可能是因为以下原因之一：

* 存储库所在表空间的块大小小于 8k 。
* `NLS_LENG_semantictics`参数设置为char。

 a| 
您必须将这些值分配给以下参数：

* `block_size=* 8192*`
* `NLS_length =*字节*`


修改参数值后，必须重新启动数据库。

有关详细信息，请参见知识库文章 2017632 。

|===


== 与数据库备份过程（ 2000 系列）关联的错误消息

下表列出了与数据库备份过程相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-02066：您不能删除或释放归档日志备份"data-logs"、因为备份与数据备份"data-logs"关联。`
 a| 
归档日志备份与数据文件备份一起进行，您尝试删除归档日志备份。
 a| 
使用`_-force_`选项删除或释放备份。



 a| 
`sMSAP-0267：您不能删除或释放归档日志备份"data-logs"、因为备份与数据备份"data-logs"关联且处于分配的保留期限内。`
 a| 
归档日志备份与数据库备份关联且处于保留期限内，您尝试删除归档日志备份。
 a| 
使用`_-force_`选项删除或释放备份。



 a| 
`sMSAP-07142：由于排除模式<exclude>模式、已排除归档日志。`
 a| 
您可以在配置文件创建或备份创建操作期间排除某些归档日志文件。
 a| 
无需执行任何操作。



 a| 
`sMSAP-07155：<count>归档的日志文件不在活动文件系统中。这些归档的日志文件不会包含在备份中。`
 a| 
在配置文件创建或备份创建操作期间，活动文件系统中不存在归档日志文件。这些归档的日志文件不会包含在备份中。
 a| 
无需执行任何操作。



 a| 
`sMSAP-07148：归档的日志文件不可用。`
 a| 
在配置文件创建或备份创建操作期间，不会为当前数据库创建任何归档日志文件。
 a| 
无需执行任何操作。



 a| 
`sMSAP-07150：未找到归档的日志文件。`
 a| 
文件系统中缺少所有归档日志文件，或者在配置文件创建或备份创建操作期间将其排除。
 a| 
无需执行任何操作。



 a| 
`sMSAP-13032：无法执行操作：备份创建。根发生原因： ORACLE-20001 ：尝试将数据库实例 dfcln1 的状态更改为 OPEN 时出错： ORACLE-20004 ：希望能够在不使用 RESETLOGS 选项的情况下打开数据库，但 Oracle 报告需要使用 RESETLOGS 选项打开数据库。为了防止意外重置日志，此过程不会继续。请确保可以在不使用RESETLOGS选项的情况下打开数据库、然后重试。`
 a| 
您尝试备份使用 -no-resetlogs 选项创建的克隆数据库。克隆的数据库不是完整的数据库。但是，您可以对克隆的数据库执行 SnapManager 操作，例如创建配置文件和备份，拆分克隆等，但 SnapManager 操作会失败，因为克隆的数据库未配置为完整的数据库。
 a| 
恢复克隆的数据库或将数据库转换为 Data Guard 备用数据库。

|===


== 数据保护错误

下表显示了与数据保护相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`已请求备份保护、但数据库配置文件没有保护策略。请更新数据库配置文件中的保护策略、或者在创建备份时不要使用"保护"选项。`
 a| 
您尝试创建对二级存储具有保护的备份；但是，与此备份关联的配置文件没有指定保护策略。
 a| 
编辑配置文件并选择保护策略。重新创建备份。



 a| 
`无法删除配置文件、因为已启用数据保护、但Protection Manager暂时不可用。请稍后重试。`
 a| 
您尝试删除已启用保护的配置文件，但 Protection Manager 不可用。
 a| 
确保在主存储或二级存储中存储相应的备份。在配置文件中禁用保护。如果 Protection Manager 再次可用，请返回到配置文件并将其删除。



 a| 
`无法列出保护策略、因为Protection Manager暂时不可用。请稍后重试。`
 a| 
在设置备份配置文件时，您对备份启用了保护，以便备份存储在二级存储上。但是， SnapManager 无法从 Protection Manager 管理控制台检索保护策略。
 a| 
暂时在配置文件中禁用保护。继续创建新配置文件或更新现有配置文件。如果 Protection Manager 再次可用，请返回到配置文件。



 a| 
`无法列出保护策略、因为未安装Protection Manager产品或未将SnapDrive 配置为使用它。请安装Protection Manager和/或配置SnapDrive。`
 a| 
在设置备份配置文件时，您对备份启用了保护，以便备份存储在二级存储上。但是， SnapManager 无法从 Protection Manager 的管理控制台检索保护策略。未安装 Protection Manager 或未配置 SnapDrive 。
 a| 
安装 Protection Manager 。配置 SnapDrive 。

返回到配置文件，重新启用保护，然后选择 Protection Manager 的管理控制台中可用的保护策略。



 a| 
`无法设置保护策略、因为Protection Manager暂时不可用。请稍后重试。`
 a| 
在设置备份配置文件时，您对备份启用了保护，以便备份存储在二级存储上。但是， SnapManager 无法从 Protection Manager 的管理控制台检索保护策略。
 a| 
暂时在配置文件中禁用保护。继续创建或更新配置文件。如果 Protection Manager 的管理控制台可用，请返回到配置文件。



 a| 
`在主机<host>上为数据库<dbname>创建新数据集<datase_name>。`
 a| 
您尝试创建备份配置文件。SnapManager 会为此配置文件创建一个数据集。
 a| 
无需执行任何操作。



 a| 
`d由于未安装Protection Manager、无法提供数据保护。`
 a| 
在设置备份配置文件时，您尝试对备份启用保护，以便将备份存储在二级存储上。但是， SnapManager 无法从 Protection Manager 的管理控制台访问保护策略。未安装 Protection Manager 。
 a| 
安装 Protection Manager 。



 a| 
`d此数据库的已创建数据集<datase_name>。`
 a| 
您已删除配置文件。SnapManager 将删除关联的数据集。
 a| 
无需执行任何操作。



 a| 
`d启用了保护且不再配置Protection Manager的配置文件。正在从SnapManager 中删除配置文件、但未在Protection Manager中清理数据集。`
 a| 
您尝试删除已启用保护的配置文件；但是， Protection Manager 不再安装，不再配置或已过期。SnapManager 将从 Protection Manager 的管理控制台删除此配置文件，但不会删除此配置文件的数据集。
 a| 
重新安装或重新配置 Protection Manager 。返回到配置文件并将其删除。



 a| 
`保留类无效。使用"smsap help backup"可查看可用保留类的列表。`
 a| 
设置保留策略时，您尝试使用无效的保留类。
 a| 
输入以下命令创建有效保留类列表：`* smsap help backup*`

使用一个可用类更新保留策略。



 a| 
`s专用保护策略不可用。使用"smsap protection-policy list"查看可用保护策略的列表。`
 a| 
在设置配置文件时，您启用了保护并输入了一个不可用的保护策略。
 a| 
输入以下命令以确定可用的保护策略：`* smsap protection-policy list*`



 a| 
`由于主机<host>上的数据库<dbname>已存在数据集、因此使用现有数据集<datase_name>。`
 a| 
您尝试创建配置文件；但是，同一数据库配置文件的数据集已存在。
 a| 
检查现有配置文件中的选项，并确保它们与新配置文件中的所需内容匹配。



 a| 
`由于主机<hostname>上已存在相同RAC数据库的实例<sid>的配置文件<profile_name>、因此使用RAC数据库<dbname>的现有数据集<datase_name>。`
 a| 
您尝试为 RAC 数据库创建配置文件；但是，同一 RAC 数据库配置文件的数据集已存在。
 a| 
检查现有配置文件中的选项，并确保它们与新配置文件中的所需内容匹配。



 a| 
`此数据库已存在保护策略为<existing_policy_name>的数据集<datase_name>。您已指定保护策略 <new_policy_name> 。数据集的保护策略将更改为 <new_policy_name> 。您可以通过更新配置文件来更改保护策略。`
 a| 
您尝试创建一个启用了保护并选择了保护策略的配置文件。但是，同一数据库配置文件的数据集已存在，但具有不同的保护策略。SnapManager 将对现有数据集使用新指定的策略。
 a| 
查看此保护策略并确定此策略是否适用于数据集。如果没有，请编辑配置文件并更改策略。



 a| 
`Protection Manager会删除SnapManager for SAP`创建的本地备份
 a| 
Protection Manager 的管理控制台会根据 Protection Manager 中定义的保留策略删除或释放 SnapManager 创建的本地备份。删除或释放本地备份时，不会考虑为本地备份设置的保留类。将本地备份传输到二级存储系统时，不会考虑为主存储系统上的本地备份设置的保留类。传输计划中指定的保留类将分配给远程备份。
 a| 
每次创建新数据集时、从Protection Manager服务器运行`dfpm dataset fix_smsap`命令。现在、备份不会根据Protection Manager管理控制台中设置的保留策略被删除。



 a| 
`您已选择对此配置文件禁用保护。这可能会删除 Protection Manager 中的关联数据集，并销毁为该数据集创建的复制关系。您也无法执行 SnapManager 操作，例如还原或克隆此配置文件的二级或三级备份。是否要继续(是/否)？`
 a| 
在从 SnapManager 命令行界面或图形用户界面更新配置文件时，您尝试禁用对受保护配置文件的保护。您可以在SnapManager 命令行界面中使用`-noprotect`选项禁用对配置文件的保护、或者在SnapManager 图形用户界面的策略属性窗口中清除*保护管理器保护策略*复选框。禁用对配置文件的保护时、SnapManager for SAP会从Protection Manager的管理控制台删除数据集、从而取消注册与该数据集关联的所有二级和三级备份副本。

删除数据集后，所有二级和三级备份副本都将成为孤立副本。Protection Manager和SnapManager for SAP均无法访问这些备份副本。无法再使用SnapManager for SAP还原备份副本。


NOTE: 即使配置文件未受保护，也会显示相同的警告消息。
 a| 
这是SnapManager for SAP中的已知问题描述 、也是在销毁数据集时Protection Manager中的预期行为。没有解决方法。需要手动管理孤立备份。

|===


== 与还原过程相关的错误消息（ 3000 系列）

下表显示了与还原过程相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-03031：还原备份<variable>需要使用还原规范、因为备份的存储资源已释放。`
 a| 
您尝试还原已释放其存储资源的备份，但未指定还原规范。
 a| 
指定还原规范。



 a| 
`sMSAP-03032：还原规范必须包含要还原的文件的映射、因为备份的存储资源已释放。需要映射的文件为：<variable> from Snapshots：<variable>`
 a| 
您尝试还原已释放其存储资源的备份以及不包含要还原的所有文件的映射的还原规范。
 a| 
更正还原规范文件，使映射与要还原的文件匹配。



 a| 
`ORACLE-30028：无法转储日志文件<filename>。此文件可能缺失 / 无法访问 / 已损坏。此日志文件不会用于恢复。`
 a| 
无法使用联机重做日志文件或归档日志文件进行恢复。发生此错误的原因如下：

* 错误消息中提及的联机重做日志文件或归档日志文件没有足够的更改编号可用于恢复。如果数据库联机而未进行任何事务，则会发生这种情况。重做日志或归档日志文件没有任何可应用于恢复的有效变更编号。
* 错误消息中提及的联机重做日志文件或归档日志文件没有足够的 Oracle 访问权限。
* 错误消息中提及的联机重做日志文件或归档日志文件已损坏， Oracle 无法读取。
* 在所述路径中未找到错误消息中提及的联机重做日志文件或归档日志文件。

 a| 
如果错误消息中提及的文件是归档日志文件，并且您手动提供了恢复功能，请确保该文件具有对 Oracle 的完全访问权限。即使该文件具有完全权限， 此消息仍会显示，归档日志文件没有任何要应用于恢复的更改编号，可以忽略此消息。



 a| 
`sMSAP-03038：无法从二级系统还原、因为存储资源仍位于主系统上。请改为从主卷还原。`
 a| 
您尝试从二级存储进行还原，但 Snapshot 副本位于主存储上。
 a| 
如果备份尚未释放，请始终从主卷进行还原。



 a| 
`sMSAP-03054：挂载备份archbkp1以馈送archivelog。DS-10001 ：连接挂载点。【错误】 flow-11019 ： ExecuteConnectionSteps 失败： SD-10028 ： SnapDrive 错误（ ID ： 2618 代码： 305 ）。无法删除以下文件。相应的卷可能为只读卷。使用较旧的快照重试此命令。[错误] flow-11010：操作正在过渡以因先前失败而中止。`
 a| 
在恢复期间， SnapManager 会尝试从二级系统挂载最新备份，以便从二级系统馈送归档日志文件。但是，如果存在任何其他备份，则恢复可以成功。但是，如果没有其他备份，则恢复可能会失败。
 a| 
请勿从主备份中删除最新的备份，以便 SnapManager 可以使用主备份进行恢复。

|===


== 与克隆进程（ 4000 系列）关联的错误消息

下表显示了与克隆过程相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-04133：转储目标不能存在`
 a| 
您正在使用 SnapManager 创建新克隆；但是，新克隆要使用的转储目标已存在。如果存在转储目标，则 SnapManager 无法创建克隆。
 a| 
在创建克隆之前，请删除或重命名旧的转储目标。



 a| 
`sMSAP-04908：不是FlexClone。`
 a| 
此克隆为 LUN 克隆。这适用于 Data ONTAP 8.1 7- 模式以及集群模式 Data ONTAP 。
 a| 
SnapManager 仅支持在 FlexClone 技术上拆分克隆。



 a| 
`sMSAP-04904：没有使用_ssplit id_id_`运行克隆拆分操作
 a| 
操作 ID 无效或未执行克隆拆分操作。
 a| 
为克隆拆分状态，结果和停止操作提供有效的拆分 ID 或拆分标签。



 a| 
`sMSAP-04906：停止克隆拆分操作失败、并出现_split—idssplit _id_`
 a| 
拆分操作已完成。
 a| 
使用`* clone split -status*`或`* clone split -result*`命令检查拆分过程是否正在进行中。



 a| 
`sMSAP-13032：无法执行操作：克隆创建。根发生原因： ORACLE-001 ：执行 SQL 时出错： [alter database open RESETLOGS ； ] 。返回的命令：ora-38856：无法将实例unn命名 实例_2 (重做线程2)标记为已启用。`
 a| 
使用以下设置从备用数据库创建克隆时，克隆创建将失败：

* 主数据库为 RAC 设置，备用数据库为独立数据库。
* 使用 RMAN 创建备份数据文件的备用。

 a| 
在创建克隆之前、在克隆规范文件中添加` no_recovery_through _resetlogs=true`参数。请参见适用于追加信息的 Oracle 文档（ ID 334899.1 ）。确保您已获得 Oracle Metalink 用户名和密码。



 a| 
`操作失败。克隆规范中的语法错误：[error：CVC-complex type.2.4c：expected elements 'value@http://www.example.com default@http://www.example.com' before the end of the content in element parameter@http://www.example.com]`
 a| 
您未在克隆规范文件中为参数提供值。
 a| 
您必须为此参数提供一个值，或者如果克隆规范文件中不需要该参数，则必须将其删除。

|===


== 与管理配置文件进程（ 5000 系列）关联的错误消息

下表显示了与克隆过程相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-20600：在存储库"repo_name"中未找到配置文件"profile1"。请运行"配置文件同步"以更新配置文件到存储库的映射。`
 a| 
如果配置文件创建失败，则无法执行转储操作。
 a| 
使用`smsapsystem dump`。

|===


== 与释放备份资源相关的错误消息（备份 6000 系列）

下表显示了与备份任务相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-06030：无法删除备份、因为备份正在使用中：<variable>`
 a| 
当备份已挂载或标记为无限制保留时、您尝试使用命令执行备份可用操作。
 a| 
卸载备份或更改无限保留策略。如果存在克隆，请将其删除。



 a| 
`sMSAP-06045：无法释放备份<variable>、因为备份的存储资源已释放`
 a| 
当备份已释放时，您尝试使用命令执行备份可用操作。
 a| 
如果备份已释放，则无法释放它。



 a| 
`sMSAP-06047：只能释放成功的备份。备份<ID>的状态为<status>。`
 a| 
当备份状态不成功时，您尝试使用命令执行备份可用操作。
 a| 
成功备份后重试。



 a| 
`sMSAP-13082：无法对备份<ID>执行操作<variable>、因为备份的存储资源已释放。`
 a| 
您尝试使用命令挂载已释放存储资源的备份。
 a| 
您不能对已释放存储资源的备份执行挂载、克隆、验证或回拨还原。

|===


== 虚拟存储接口错误（虚拟存储接口 8000 系列）

下表显示了与虚拟存储接口任务相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-08017发现/.`的存储时出错
 a| 
SnapManager 尝试查找存储资源、但在`root/`目录中发现了数据文件、控制文件或日志。这些文件应位于子目录中。根文件系统可能是本地计算机中的硬盘驱动器。SnapDrive 无法在此位置创建 Snapshot 副本，并且 SnapManager 无法对这些文件执行操作。
 a| 
检查数据文件、控制文件或重做日志是否位于`root`目录中。如果是，请将其移动到正确的位置，或者在正确的位置重新创建控制文件或重做日志。基本挂载点始终为

* `/oracle/<sid>`基于UNIX的环境
* 在基于Windows的环境中、`驱动器：]\oracle\<sid>`


SAP使用四个具有两个成员的重做日志组：

* 一个成员存储在原始日志｛A_B｝中。
* 另一个成员将镜像到镜像日志｛A_B｝。


|===


== 与滚动升级过程（ 9000 系列）相关的错误消息

下表显示了与滚动升级过程相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-09234：旧存储库中不存在以下主机。<主机名>。`
 a| 
您尝试执行主机滚动升级，而先前的存储库版本不存在此升级。
 a| 
在早期版本的SnapManager 命令行界面中使用`repository show-repository`命令检查主机是否位于先前的存储库中。



 a| 
`sMSAP-09255：新存储库中不存在以下主机。<主机名>。`
 a| 
您尝试执行主机回滚，新存储库版本中不存在此主机。
 a| 
在更高版本的SnapManager 命令行界面中使用`repository show-repository`命令检查主机是否位于新存储库中。



 a| 
`sMSAP-09256：不支持回滚、因为指定主机<hostname>存在新的配置文件<proFilames>.for the specified hosts <hostname>.`
 a| 
您已尝试回滚包含存储库中现有新配置文件的主机。但是，早期 SnapManager 版本的主机中不存在这些配置文件。
 a| 
在回滚之前，删除较新版本或已升级版本的 SnapManager 中的新配置文件。



 a| 
`sMSAP-09257：不支持回滚、因为备份<backupid>已挂载到新主机中。`
 a| 
您尝试回滚已挂载备份的较高版本 SnapManager 主机。这些备份不会挂载在早期版本的 SnapManager 主机中。
 a| 
卸载较高版本的 SnapManager 主机中的备份，然后执行回滚。



 a| 
`sMSAP-09258：不支持回滚、因为备份<backupid>已卸载到新主机中。`
 a| 
您尝试回滚包含正在卸载的备份的较高版本 SnapManager 主机。
 a| 
在更高版本的 SnapManager 主机中挂载备份，然后执行回滚。



 a| 
`sMSAP-09298：无法更新此存储库、因为它已在更高版本中具有其他主机。请改为对所有主机执行滚动升级。`
 a| 
您对单个主机执行了滚动升级，然后更新了该主机的存储库。
 a| 
对所有主机执行滚动升级。



 a| 
`sMSAP-09297：启用约束时出错。存储库可能处于不一致状态。建议还原您在当前操作之前所做的存储库备份。`
 a| 
如果存储库数据库处于不一致状态，则您尝试执行滚动升级或回滚操作。
 a| 
还原先前备份的存储库。

|===


== 执行操作（ 12 ， 000 系列）

下表显示了与操作相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-12347 [错误]：SnapManager 服务器未在主机<主机>和端口<端口>上运行。请在运行SnapManager 服务器的主机上运行此命令。`
 a| 
在设置配置文件时，您输入了有关主机和端口的信息。但是， SnapManager 无法执行这些操作，因为 SnapManager 服务器未在指定的主机和端口上运行。
 a| 
在运行 SnapManager 服务器的主机上输入命令。您可以使用`lsnrctl status`命令检查端口、并查看运行数据库的端口。如果需要，可在 backup 命令中更改端口。

|===


== 执行流程组件（ 13 ， 000 系列）

下表显示了与 SnapManager 的进程组件相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-13083：值为"x"的Snapname模式包含字母、数字、下划线、短划线和花括号以外的字符。`
 a| 
在创建配置文件时，您自定义了 Snapname 模式；但是，您包含了不允许使用的特殊字符。
 a| 
删除字母，数字，下划线，短划线和花括号以外的特殊字符。



 a| 
`sMSAP-13084：值为"x"的Snapname模式不包含相同数量的左括号和右括号。`
 a| 
创建配置文件时，您自定义了 Snapname 模式；但是，左括号和右括号不匹配。
 a| 
在 Snapname 模式中输入匹配的括号和右括号。



 a| 
`sMSAP-13085：值为"x"的Snapname模式包含无效变量名"y"。`
 a| 
在创建配置文件时，您自定义了 Snapname 模式；但是，您包含了一个不允许的变量。
 a| 
删除有问题的变量。要查看可接受变量的列表，请参见 xref:concept-snapshot-copy-naming.adoc[Snapshot 副本命名]。



 a| 
`s值为"x"的MSAP-13086 Snapname模式必须包含变量"smid"。`
 a| 
在创建配置文件时、您自定义了Snapname模式；但是、您省略了所需的`_SMID_`变量。
 a| 
插入所需的`_SMID_`变量。



 a| 
`sMSAP-13902：克隆拆分启动失败。`
 a| 
出现此错误的原因可能有多种：

* 卷中没有空间。
* SnapDrive 未运行。
* 克隆可以是 LUN 克隆。
* FlexVol 卷具有受限的 Snapshot 副本。

 a| 
使用`* clone split -estim*`命令检查卷中的可用空间。确认 FlexVol 卷没有受限的 Snapshot 副本。



 a| 
`sMSAP-13904：克隆拆分结果失败。`
 a| 
这可能是由于 SnapDrive 或存储系统出现故障所致。
 a| 
尝试处理新克隆。



 a| 
`sMSAP-13906：克隆标签_clone-label或ID _clone-id_的拆分操作已在运行。`
 a| 
您正在尝试拆分已拆分的克隆。
 a| 
克隆已拆分，并且将删除与克隆相关的元数据。



 a| 
`sMSAP-13907：克隆标签_clone-label或ID _clone-id_`的拆分操作已在运行。
 a| 
您正在尝试拆分正在进行拆分的克隆。
 a| 
您必须等待拆分操作完成。

|===


== 与 SnapManager 实用程序（ 14 ， 000 系列）关联的错误消息

下表显示了与 SnapManager 实用程序相关的常见错误：

[cols="1a,1a,1a"]
|===
| 错误消息 | 说明 | 解决方法： 


 a| 
`sMSAP-14501：邮件ID不能为空。`
 a| 
您未输入电子邮件地址。
 a| 
输入有效的电子邮件地址。



 a| 
`sMSAP-14502：邮件主题不能为空。`
 a| 
您未输入电子邮件主题。
 a| 
输入相应的电子邮件主题。



 a| 
`sMSAP-14506：邮件服务器字段不能为空。`
 a| 
您未输入电子邮件服务器主机名或 IP 地址。
 a| 
输入有效的邮件服务器主机名或 IP 地址。



 a| 
`sMSAP-14507：邮件端口字段不能为空。`
 a| 
您未输入电子邮件端口号。
 a| 
输入电子邮件服务器端口号。



 a| 
`sMSAP-14508：发件人邮件ID不能为空。`
 a| 
您未输入发件人的电子邮件地址。
 a| 
输入有效的发件人电子邮件地址。



 a| 
`sMSAP-14509：用户名不能为空。`
 a| 
您启用了身份验证，但未提供用户名。
 a| 
输入电子邮件身份验证用户名。



 a| 
`sMSAP-14510：密码不能为空。请输入密码。`
 a| 
您已启用身份验证，但未提供密码。
 a| 
输入电子邮件身份验证密码。



 a| 
`sMSAP-14550：电子邮件状态<成功/失败>。`
 a| 
端口号，邮件服务器或接收方的电子邮件地址无效。
 a| 
在电子邮件配置期间提供正确的值。



 a| 
`sMSAP-14559：发送电子邮件通知失败：<error>.`
 a| 
这可能是由于端口号无效，邮件服务器无效或收件人的邮件地址无效所致。
 a| 
在电子邮件配置期间提供正确的值。



 a| 
`sMSAP-14560：通知失败：通知配置不可用。`
 a| 
通知发送失败，因为通知配置不可用。
 a| 
添加通知配置。



 a| 
`sMSAP-14565：时间格式无效。请以HH：MM`格式输入时间格式
 a| 
您输入的时间格式不正确。
 a| 
以 HH ： MM 格式输入时间。



 a| 
`sMSAP-14566：日期值无效。有效日期范围为1-31。`
 a| 
配置的日期不正确。
 a| 
日期应介于 1 到 31 之间。



 a| 
`sMSAP-14567：日期值无效。有效日期范围为1-7.`
 a| 
配置的日期不正确。
 a| 
输入日期范围 1 到 7 。



 a| 
`sMSAP-14569：服务器无法启动摘要通知计划。`
 a| 
由于未知原因， SnapManager 服务器已关闭。
 a| 
启动 SnapManager 服务器。



 a| 
`sMSAP-14570：摘要通知不可用。`
 a| 
您尚未配置摘要通知。
 a| 
配置摘要通知。



 a| 
`sMSAP-14571：无法同时启用配置文件和摘要通知。`
 a| 
您已选择配置文件和摘要通知选项。
 a| 
启用配置文件通知或摘要通知。



 a| 
`sMSAP-14572：为通知提供成功或失败选项。`
 a| 
您尚未启用成功或失败选项。
 a| 
您必须选择成功或失败选项，或者同时选择这两者。

|===


== 常见的 SnapDrive for UNIX 错误消息

下表显示了与 SnapDrive for UNIX 相关的常见错误：

[cols="1a,1a"]
|===
| 错误消息 | 说明 


 a| 
`0001-136管理员错误：无法登录到存储器：<filer>请为<filer>`设置用户名和/或密码
 a| 
初始配置错误



 a| 
`0001-382管理员错误：多路径重新扫描失败`
 a| 
LUN 发现错误



 a| 
`0001-462管理员错误：无法取消配置<LUN>的多路径：spd5：无法停止设备。设备繁忙。`
 a| 
LUN 发现错误



 a| 
`0001-476管理员错误：无法发现与...`关联的设备
 a| 
LUN 发现错误



 a| 
`0001-680管理员错误：主机操作系统需要更新内部数据、才能创建或连接LUN。使用"LUN SnapDrive 配置准备LUN"或手动更新此信息...`
 a| 
LUN 发现错误



 a| 
`0001-710管理员错误：操作系统刷新LUN失败...`
 a| 
LUN 发现错误



 a| 
`0001-817管理员错误：无法创建卷克隆... ：未获得FlexClone许可`
 a| 
初始配置错误



 a| 
`0001-817管理员错误：无法创建卷克隆... ：由于无法保证克隆`的空间、请求失败。
 a| 
空间问题描述



 a| 
`0001-878管理员错误：未找到HBA助手。涉及 LUN 的命令应失败。`
 a| 
LUN 发现错误



 a| 
`sMSAP-12111：执行SnapDrive 命令SnapDrive command>"时出错：< SnapDrive error>`
 a| 
SnapDrive for UNIX 一般错误

|===