---
permalink: unix-administration/task-update-profiles.html 
sidebar: sidebar 
keywords: update, profile, modify, password, database, operating, system, os, authentication, updating, information, host, database, oracle, updating 
summary: 您可以更新配置文件以修改配置文件密码，要保留的备份数，对数据库的访问，对数据库进行身份验证的操作系统（ OS ）身份验证（反之亦然）以及有关主机的信息。如果 Oracle 数据库密码信息发生更改，您还必须在配置文件中更改此信息。 
---
= 更新配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更新配置文件以修改配置文件密码，要保留的备份数，对数据库的访问，对数据库进行身份验证的操作系统（ OS ）身份验证（反之亦然）以及有关主机的信息。如果 Oracle 数据库密码信息发生更改，您还必须在配置文件中更改此信息。

* 关于此任务 *

如果在配置文件上启用了保护策略，则无法使用 SnapManager 更改此策略。存储管理员必须使用 Protection Manager 的控制台更改此策略。

使用SnapManager (3.2或更高版本)、您可以使用`-separate -archivelog-backups`选项更新配置文件、以便将归档日志备份与数据文件备份分开。您可以为归档日志备份指定单独的保留期限和保护策略。通过 SnapManager ，您可以将归档日志备份与联机数据库备份一起使用。您还可以同时创建联机数据文件备份和归档日志备份以进行克隆。创建联机数据文件备份时，系统会立即创建归档日志备份以及数据文件。

.步骤
. 输入以下命令：
+
`* smsap profile update -profile _profile_[-new-profile _new_profile_name_](-profile-password _profile_password_）-database-dbname _db_dbname_-host _db_host_(-SID _db_sid_sid_])(-login -stance _db_username -password -password _sm_asn_sman) `每周(-count _n_）个持续时间_m_m_]]-monthly (-count _n_）个(-duration _m_m_）个(-comment _comment_）个(-snapname -pattern _pattern_）个(-protect (-protection-policy address_policy_name_）个月)个月(-unip-no_address2个月

+
此命令的其他选项如下：

+
``、``、-force]、-noprompt]、

+
````(-quiet | verbose)

+
[cols="2a,4a"]
|===
| 如果您要 ... | 那么 ... 


 a| 
* 更改配置文件以使用操作系统身份验证 *
 a| 
请指定以下内容，而不是添加用户名，密码和端口：

** `-osaccount _account_name_`作为操作系统帐户的名称
** `-osgroup _osgroup_`作为与操作系统帐户关联的组、通常是用于安装Oracle的帐户




 a| 
* 使用自动存储管理（ Automatic Storage Management ， ASM ）实例身份验证创建配置文件 *
 a| 
指定 ASM 实例身份验证的凭据。

** `-asmusername _asminstance_username_`是用于登录到ASM实例的用户名。
** `-asmpassword _asminstance_password_`是用于登录到ASM实例的密码。




 a| 
* 使用目录作为 Oracle Recovery Manager （ RMAN ）存储库，或者您要删除 RMAN*
 a| 
指定以下选项和变量：

** `-tnsnamname _tnsnames_`作为在`tnsnames.ora`文件中定义的tnsnamname。
** `-login -username _username_`作为连接到RMAN目录所需的用户名。
+
如果未指定， SnapManager 将使用操作系统身份验证信息。您不能对 Real Application Clusters （ RAC ）数据库使用操作系统身份验证。

** `-password _password_`作为连接到RMAN目录所需的RMAN密码。
** `-controlfile`使用控制文件作为RMAN存储库。
** `-remove-RMAN`用于删除RMAN。




 a| 
* 更改配置文件中数据库备份的备份保留策略 *
 a| 
指定保留类的保留计数或保留期限，或者同时指定这两者以更改保留策略。持续时间以类的单位为单位（例如，小时表示每小时，天表示每天）。

** `-每小时`是每小时保留类、其中`(-count _n_）(-duration _m_）]`分别是保留计数和保留持续时间。
** `-每日`是每日保留类、其中`(-count _n_）(-duration _m_）]`分别是保留计数和保留期限。
** `-每周`是每周保留类、其中`(-count _n_）【-duration _m_]]`分别是保留计数和保留期限。
** `-每月`是每月保留类别、其中`(-count _n_）(-duration _m_）]`分别是保留计数和保留期限。




 a| 
* 禁用配置文件的备份保护 *
 a| 
指定`-noprotect`以不保护使用配置文件创建的数据库备份。对于已启用`保护`的配置文件、如果要禁用保护、则会显示一条警告消息、指出此操作将删除数据集、并且您将无法还原或克隆此配置文件的备份。



 a| 
* 为数据库操作的完成状态启用电子邮件通知 *
 a| 
指定以下选项和变量：

** 使用`摘要通知`、您可以为存储库数据库下的多个配置文件配置摘要电子邮件通知。
** 使用` notification`、您可以收到有关配置文件数据库操作完成状态的电子邮件通知。
** `-success -email _email_address2_`使您能够在使用新配置文件或现有配置文件成功执行数据库操作后收到电子邮件通知。
** 使用`-failure -email _email_address2_`、您可以收到有关使用新配置文件或现有配置文件执行的数据库操作失败的电子邮件通知。
** `-Subject _Subject_text_`指定创建新配置文件或现有配置文件时电子邮件通知的主题文本。如果未为存储库配置通知设置、而您正在尝试使用命令行界面(CLI)配置配置配置文件或摘要通知、则控制台日志中会记录以下消息：`sMSAP-145777：Notification Settings not configured`。
+
如果您已配置通知设置、并且正在尝试使用命令行界面配置摘要通知、而不为存储库启用摘要通知、则控制台日志中会记录以下消息：`sMSAP-14575：summary notification configuration not available for this repository`





 a| 
* 更新配置文件以单独创建归档日志文件的备份 *
 a| 
指定以下选项和变量：

** 使用`-separate-archivelog-backups`可以分别为归档日志文件和数据库文件创建备份。
+
指定此选项后，您可以创建仅数据文件备份或仅归档文件备份。您不能创建完整备份。此外，不能通过分离备份来还原配置文件设置。SnapManager 会根据在仅执行归档日志备份之前创建的备份的保留策略保留这些备份。

** `-retain-archivelog-backups`设置归档日志备份的保留期限。
+

NOTE: 如果您是首次更新配置文件、则可以使用`-separate -archivelog-backups`选项将归档日志备份与数据文件备份分开；您必须使用`-retain-archivelog-backups`选项提供归档日志备份的保留期限。在稍后更新配置文件时，可以选择设置保留期限。

** `保护`在Data Fabric Manager (DFM)服务器中创建应用程序数据集、并添加与数据库、数据文件、控制文件和归档日志相关的成员。
+
如果数据集存在，则在创建配置文件时会重复使用该数据集。

** `-protection-policy`将保护策略设置为归档日志备份。
** `-include-with -online backups`指定归档日志备份与数据库备份一起提供。
** `-no-include-with -online backups`指定归档日志文件备份不随数据库备份一起提供。




 a| 
* 更改目标数据库的主机名 *
 a| 
指定`-host _new_db_host_`以更改配置文件的主机名。



 a| 
* 在执行配置文件更新操作后收集转储文件 *
 a| 
指定`-dump`选项。

|===
. 要查看更新后的配置文件、请输入以下命令：`smsap profile show`

