---
permalink: unix-administration/task-delete-backups.html 
sidebar: sidebar 
keywords: delete, backup, free, space, remove, snapshot, copies, copy, volume, deleting 
summary: 您必须删除不再需要的备份，这样可以释放这些备份占用的空间。如果删除备份，则每个卷的 Snapshot 副本数将减少达到 255 个限制的可能性。 
---
= 删除备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须删除不再需要的备份，这样可以释放这些备份占用的空间。如果删除备份，则每个卷的 Snapshot 副本数将减少达到 255 个限制的可能性。

* 您需要的内容 *

* 您必须确保未使用此备份创建克隆。


* 关于此任务 *

删除受保护的备份时， SnapManager 会从二级存储和 SnapManager 存储库中删除该备份。下表显示了删除本地备份时在主存储和二级存储上执行的操作：

[cols="2a,1a,3a,3a,4a"]
|===
| 保护状态 | 本地状态 | 对主存储执行的操作 | 对二级存储执行的操作 | 说明 


 a| 
未请求（待保护）
 a| 
exists
 a| 
删除 Snapshot 副本
 a| 
无需执行任何操作
 a| 
SnapManager 会删除本地备份。



 a| 
已释放
 a| 
无需执行任何操作
 a| 
无需执行任何操作
 a| 
本地备份已释放。如果删除已释放的备份，则备份元数据将从存储库中删除。



 a| 
不受保护
 a| 
exists
 a| 
删除 Snapshot 副本
 a| 
无需执行任何操作
 a| 
无论本地备份是否受到保护， SnapManager 都会删除该备份。



 a| 
已释放
 a| 
无需执行任何操作
 a| 
无需执行任何操作
 a| 
本地备份已释放。如果删除已释放的备份，则备份元数据将从存储库中删除。



 a| 
受保护
 a| 
exists
 a| 
删除 Snapshot 副本
 a| 
SnapManager 会删除二级存储上的备份
 a| 
SnapManager 会删除本地备份和二级副本。



 a| 
已释放
 a| 
无需执行任何操作
 a| 
SnapManager 可释放二级存储上的备份
 a| 
SnapManager 会删除本地备份和二级副本。

|===
如果您尝试删除受二级存储保护的备份，则 Snapshot 副本可能会被标记为删除，并稍后由 Protection Manager 删除。

您可以删除无限制保留的备份，而不更改保留类。

您可以选择在备份删除操作成功或失败后收集转储文件。

如果要删除归档日志备份，则需要检查为归档日志备份设置的保留期限。如果归档日志备份处于保留期限内，并且恢复已还原的数据库需要归档日志文件，则无法删除归档日志备份。

.步骤
. 输入以下命令以验证操作是否已完成：
+
`* smsap操作列表-profile _profile_name_-dump-quiet verbose *`

. 要删除备份、请输入以下命令：
+
`* smsap backup delete -profile _profile_name_"-label _label_[data _-archivelogs]_- id _id_____-所有](-force][-dump](-quiet _-verbose)*`

+
使用 -force 选项强制删除备份。强制删除操作不完整的备份可能会使备份处于不一致状态。


