---
permalink: unix-administration/task-use-snapmanager-for-oraclesnapmanager-for-sapto-restore-a-local-backup-on-primary-storage.html 
sidebar: sidebar 
keywords: restore, local, backup, exist, primary, storage, entire, process, perform, snapmanager, sap 
summary: 您可以还原主存储上的本地备份。整个过程使用适用于SAP的SnapManager 执行。 
---
= 使用SnapManager for SAP在主存储上还原本地备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以还原主存储上的本地备份。整个过程使用适用于SAP的SnapManager 执行。

* 关于此任务 *

您还可以预览有关备份还原过程的信息。您可能希望执行此操作以查看有关备份的还原资格的信息。SnapManager 会分析备份上的数据，以确定是否可以使用基于卷的还原或基于文件的还原方法来完成还原过程。

还原预览显示以下信息：

* 将使用哪种还原机制（快速还原，存储端文件系统还原，存储端文件还原或主机端文件副本还原）来还原每个文件。
* 为什么不使用更高效的机制来还原每个文件。


在还原计划预览期间， SnapManager 不会还原任何内容。预览最多可显示 20 个文件的信息。

如果要预览数据文件的还原，但未挂载数据库，则 SnapManager 会挂载数据库。如果无法挂载数据库，则操作将失败， SnapManager 会将数据库返回到其原始状态。

.步骤
. 从*存储库*树中、右键单击要还原的备份、然后选择*还原*。
. 在还原和恢复向导欢迎页面上，单击 * 下一步 * 。
. 在*还原配置信息*页面上、选择*使用控制文件完成数据文件/表空间还原*。
. 单击 * 如果需要，允许关闭数据库 * 。
+
SnapManager 会根据需要更改数据库状态。例如，如果数据库处于脱机状态且需要联机，则 SnapManager 会强制其联机。

. 在*恢复配置信息*页面上、单击*所有日志*。
+
SnapManager 会将数据库还原并恢复到最后一个事务，并应用所有必需的日志。

. 在*还原源位置配置*页面上、查看有关主备份的信息、然后单击*下一步*。
+
如果备份仅存在于主存储上，则 SnapManager 会从主存储还原备份。

. 在*卷还原配置信息*页面上、选择*尝试卷还原*以尝试卷还原方法。
. 单击 * 回退到基于文件的还原 * 。
+
这样，如果无法使用卷还原方法， SnapManager 就可以使用基于文件的还原方法。

. 单击 * 预览 * 可查看快速还原的资格检查以及有关强制检查和可覆盖检查的信息。
. 在*执行操作*页面上、验证输入的信息、然后单击*还原*。
. 要查看有关此过程的详细信息，请单击 * 操作详细信息 * 。

