---
permalink: unix-administration/task-use-protection-manager-to-configure-a-secondary-backup-protection-policy.html 
sidebar: sidebar 
keywords: configure, configuring, backup, schedule, storage, administrator, protect, protection, manager, secondary, policy 
summary: 配置备份计划后，存储管理员会配置一个受保护的备份存储策略，其中将包含该计划。 
---
= 使用Protection Manager配置二级备份保护策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
配置备份计划后，存储管理员会配置一个受保护的备份存储策略，其中将包含该计划。

* 您需要的内容 *

在配置保护策略之前，存储管理员会向 DBA 配对节点授予以下信息：

* 为二级存储指定的保留期限
* 所需的二级存储保护类型


* 关于此任务 *

DBA合作伙伴可以在SnapManager for SAP中列出创建的保护策略、并将其分配给要保护的数据的数据库配置文件。

. 转到 Protection Manager 的 NetApp 管理控制台。
. 从菜单栏中，单击 * 策略 * > * 保护 * > * 概述 * 。
+
此时将显示保护策略窗口中的概述选项卡。

. 单击*添加策略*以启动*添加保护策略*向导。
. 完成向导，并执行以下步骤：
+
.. 指定描述性策略名称。
+
在此示例中，输入 * 技术公司薪资数据： backup* 和问题描述，然后单击 * 下一步 * 。

.. 选择一个基本策略。
+
在此示例中，选择 * 备份 * ，然后单击 * 下一步 * 。

.. 在*主数据*节点策略属性表中、接受默认设置并单击*下一步*。
+

NOTE: 在此示例中，将应用在 SnapManager 中配置的本地备份计划。使用此方法指定的任何本地备份计划都将被忽略。

.. 在*要备份的主数据*连接属性表中、选择一个备份计划。
+
在此示例中，选择 * 薪资星期六凌晨 1 点加每天晚上 7 点 * 作为备份计划，然后单击 * 下一步 * 。

+
在此示例中，您选择的计划既包括先前配置的每周计划，也包括每日计划。

.. 在*备份策略*属性表中、指定备份节点的名称以及每日、每周或每月备份的保留时间。
+
在此示例中，将每天备份保留时间指定为 10 天，将每周备份保留时间指定为 52 周。完成每个属性表后，单击 * 下一步 * 。

+
完成所有属性表后，添加保护策略向导将显示要创建的保护策略的摘要表。



. 单击 * 完成 * 以保存所做的更改。


* 结果 *

在为 Protection Manager 配置的其他策略中，列出了 * 技术公司薪资数据：备份 * 保护策略。

* 完成后 *

现在、DBA合作伙伴可以在为要保护的数据创建数据库配置文件时使用SnapManager for SAP列出并分配此策略。
