---
permalink: unix-administration/task-use-protection-manager-to-configure-secondary-backup-schedules.html 
sidebar: sidebar 
keywords: support, backup, database, secondary, storage, administrator, protection, manager, configure, schedule 
summary: 为了支持将数据库备份到二级存储，存储管理员使用 Protection Manager 配置备份计划。 
---
= 使用Protection Manager配置二级备份计划
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了支持将数据库备份到二级存储，存储管理员使用 Protection Manager 配置备份计划。

* 您需要的内容 *

在配置二级备份计划之前，存储管理员会向 DBA 配对节点授予以下信息：

* DBA 希望二级备份遵循的计划。
+
在这种情况下，每天晚上 7 点进行一次备份每周一次的备份在星期六凌晨 1 点进行



.步骤
. 转到 Protection Manager 的 NetApp 管理控制台。
. 从菜单栏中，单击 * 策略 * > * 保护 * > * 计划 * 。
+
此时将显示保护策略窗口的计划选项卡。

. 在计划列表中选择每日计划 * 每天晚上 8 ： 00 点 * 。
. 单击 * 复制 * 。
+
列表中将显示一个新的每日计划 * 每天晚上 8 ： 00 的副本 * 。已选择此选项。

. 单击 * 编辑 * 。
+
此时将打开编辑每日计划属性表并显示计划选项卡。

. 将计划名称更改为 * 每天晚上 7 点发放工资 * ，更新问题描述，然后单击 * 应用 * 。
+
您所做的更改将被保存。

. 单击 * 每日事件 * 选项卡。
+
计划的当前每日备份时间为晚上 8 ： 00将显示

. 单击 * 添加 * 并在新时间字段中输入 * ： 7 ： 00 PM* ，然后单击 * 应用 * 。
+
该计划的当前每日备份时间现在为晚上 7 ： 00

. 单击 * 确定 * 保存更改并退出属性表。
+
新的每日计划 * 每天晚上 7 点的薪资 * 将显示在计划列表中。

. 在计划列表中选择每周计划 * 星期日在晚上 8 ： 00 加上每日 * 。
. 单击 * 复制 * 。
+
列表中将显示一个新的每周计划，即 * 在晚上 8 ： 00 复制星期日加上每日 * 。已选择此选项。

. 单击 * 编辑 * 。
+
此时将打开编辑每周计划属性表并显示计划选项卡。

. 将计划名称更改为 * 星期六凌晨 1 点加每天晚上 7 点 * 的薪资，然后更新问题描述。
. 从 * 每日计划 * 下拉列表中，选择刚刚创建的每日计划 * 每天晚上 7 点发放工资 * 。
+
选择 * 每天 7 点工资 * 意味着，此计划定义在对策略应用 * 星期六凌晨 1 点加每天晚上 7 点 * 计划时，何时发生每日操作。

. 单击 * 确定 * 保存更改并退出属性表。
+
新的每周计划 * 薪资星期六凌晨 1 点加上每天晚上 7 点 * 将显示在计划列表中。


