---
settings:
  name: SnapManager for SAP
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: SnapManager for SAP文档
    url: "/index.html"
  - title: 发行说明
    url: "/reference-releasenotes.html"
  - section: unix-installation-cmode
  - section: unix-installation-7mode
  - section: unix-administration
  - section: windows
  - title: 法律声明
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 入门
    links:
    - title: 产品概述
      url: "/unix-installation-cmode/reference-smsap-isg-product-overview.html"
    - title: 发行说明
      url: reference-releasenotes.html
  - title: 管理
    links:
    - title: 配置适用于UNIX的SnapManager
      url: "/unix-administration/concept-configuring-snapmanager-for-oraclesap.html"
    - title: 配置适用于Windows的SnapManager
      url: "/windows/concept-configuring-snapmanager-for-oraclesap.html"
  - title: 安装和设置
    links:
    - title: 部署工作流(7-模式)
      url: "/unix-installation-7mode/reference-smsap-isg-deployment-workflow.html"
    - title: 部署工作流(集群模式)
      url: "/unix-installation-cmode/reference-smsap-isg-deployment-workflow.html"
  - title: 更多资源
    links:
    - title: NetApp 支持
      url: https://mysupport.netapp.com/site/global/dashboard
    - title: NetApp 社区
      url: https://community.netapp.com/
