---
permalink: unix-installation-cmode/concept-smsap-isg-defining-a-backup-strategy.html 
sidebar: sidebar 
keywords: define, backup, strategy, create, successful, restore, database, snapmanager, service, level, agreement, sla 
summary: 在创建备份之前定义备份策略可确保您已备份成功还原数据库。SnapManager 提供灵活的粒度备份计划，以满足您的服务级别协议（ SLA ）要求。 
---
= 定义备份策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在创建备份之前定义备份策略可确保您已备份成功还原数据库。SnapManager 提供灵活的粒度备份计划，以满足您的服务级别协议（ SLA ）要求。


NOTE: 有关 SnapManager 最佳实践，请参见 _TR 3761_ 。



== 您需要哪种 SnapManager 备份模式？

SnapManager 支持两种备份模式：

|===
| 备份模式 | Description 


 a| 
联机备份
 a| 
在数据库处于联机状态时创建数据库备份。此备份模式也称为热备份。



 a| 
脱机备份
 a| 
在数据库处于挂载或关闭状态时创建数据库备份。此备份模式也称为冷备份。

|===


== 您需要哪种类型的 SnapManager 备份？

SnapManager 支持三种类型的备份：

|===
| 备份类型 | Description 


 a| 
完整备份
 a| 
创建整个数据库的备份，其中包括所有数据文件，控制文件和归档日志文件。



 a| 
部分备份
 a| 
创建选定数据文件，控制文件，表空间和归档日志文件的备份



 a| 
仅归档日志备份
 a| 
仅创建归档日志文件的备份。在创建配置文件时，必须选择 * 单独备份归档日志 * 。

|===


== 您需要哪种类型的数据库配置文件？

SnapManager 会根据数据库配置文件是否将归档日志备份与数据文件备份分隔开来创建备份。

|===
| 配置文件类型 | Description 


 a| 
一个数据库配置文件，用于对数据文件和归档日志进行组合备份
 a| 
用于创建：

* 完整备份，包含所有数据文件，归档日志文件和控制文件
* 包含选定数据文件，表空间，归档日志文件和控制文件的部分备份




 a| 
用于归档日志备份和数据文件备份的单独数据库配置文件
 a| 
用于创建：

* 将具有不同标签的备份组合在一起，用于数据文件备份和归档日志备份
* 所有数据文件以及控制文件的纯数据备份
* 选定数据文件或表空间以及控制文件的部分纯数据备份
* 仅归档日志备份


|===


== Snapshot 副本应使用哪些命名约定？

通过备份创建的 Snapshot 副本可以遵循自定义命名约定。可以使用自定义文本或内置变量（例如配置文件名称，数据库名称和 SnapManager 提供的数据库 SID ）来创建命名约定。您可以在创建策略时创建命名约定。


NOTE: 您必须在命名格式中包含 SMID 变量。SMID 变量创建唯一的 Snapshot 标识符。

Snapshot 副本命名约定可以在创建配置文件期间或之后进行更改。更新后的模式仅适用于尚未创建的 Snapshot 副本；现有 Snapshot 副本将保留先前的模式。



== 您希望在主存储系统和二级存储系统上保留备份副本多长时间？

备份保留策略用于指定要保留的成功备份数。您可以在创建策略时指定保留策略。

您可以选择 " 每小时 " ， " 每日 " ， " 每周 " ， " 每月 " 或 " 无限制 " 作为保留类。对于每个保留类，您可以同时或单独指定保留计数和保留期限。

* 保留数量决定了应保留的特定保留类的最小备份数。
+
例如，如果备份计划为 _daily_ 且保留计数为 _10_ ，则会保留 10 个每日备份。

+

NOTE: Data ONTAP 允许您保留的最大 Snapshot 副本数为 255 。默认情况下，在达到最大限制后，创建新 Snapshot 副本将失败。但是，您可以在 Data ONTAP 中配置轮换策略以删除旧的 Snapshot 副本。

* 保留期限用于确定备份应保留的最短天数。
+
例如，如果备份计划为 _daily_ 且保留期限为 _10_ ，则会保留 10 天的每日备份。



如果设置了 SnapMirror 复制，则保留策略将在目标卷上镜像。


NOTE: 要长期保留备份副本，应使用 SnapVault 。



== 是否要使用源卷或目标卷验证备份副本？

如果使用 SnapMirror 或 SnapVault ，则可以使用 SnapMirror 或 SnapVault 目标卷上的 Snapshot 副本而不是主存储系统上的 Snapshot 副本来验证备份副本。使用目标卷进行验证可减少主存储系统上的负载。
