---
permalink: unix-installation-cmode/reference-trademark.html 
sidebar: sidebar 
keywords: trademark, information 
summary: Trademark information 
---
= Trademark information
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Active IQ、 AltaVault、Arch Design、ASUP、 AutoSupport、Campaign Express、Clustered Data ONTAP、Customer Fitness、 Data ONTAP、DataMotion、Element、Fitness、 Flash Accel、Flash Cache、Flash Pool、 FlexCache、 FlexClone、 FlexPod、FlexScale、FlexShare、 FlexVol、FPolicy、Fueled by SolidFire、GetSuccessful、Helix Design、LockVault、Manage ONTAP、 MetroCluster、 MultiStore、 NetApp、 NetApp Insight、 OnCommand、 ONTAP、ONTAPI、 RAID DP、 RAID-TEC、 SANscreen、 SANshare、 SANtricity、 SecureShare、Simplicity、Simulate ONTAP、Snap Creator、 SnapCenter、 SnapCopy、 SnapDrive、 SnapIntegrator、 SnapLock、 SnapManager、 SnapMirror SnapMover、 SnapProtect、 SnapRestore、Snapshot、 SnapValidator、 SnapVault、 SolidFire、 SolidFire Helix、 StorageGRID、 SyncMirror、 Tech OnTap、Unbound Cloud、 WAFL和其他名称是NetApp, Inc. 在美国和/或其他国家/地区的商标或注册商标。所有其他品牌或产品均为其各自所有者的商标或注册商标，应予同样对待。NetApp商标的最新列表可在网上查阅。

http://www.netapp.com/us/legal/netapptmlist.aspx[]
