---
permalink: unix-installation-cmode/task-smsap-isg-schedule-recurring-backups.html 
sidebar: sidebar 
keywords: 'schedule, operation, backup, initiate, automatic, regular, interval, snapmanager, hourly, daily, weekly, monthly, one-time, basis, scheduling, recur summary: You can schedule backup operations so that the backups are initiated automatically at regular intervals. SnapManager allows you to schedule backups on an hourly, daily, weekly, monthly, or one-time basis.' 
---
= 计划重复备份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以计划备份操作，以便定期自动启动备份。使用 SnapManager ，您可以按每小时，每天，每周，每月或一次性计划备份。



== 关于此任务

您可以为一个数据库分配多个备份计划。但是，在为同一数据库计划多个备份时，必须确保不会同时计划备份。

以下步骤显示了如何使用 SnapManager 用户界面（ UI ）为数据库创建备份计划。如果您愿意，也可以使用命令行界面（ CLI ）。有关如何使用命令行界面计划备份的信息、请参见适用于UNIX_的_SAP SnapManager 管理指南。

.步骤
. 从存储库树中，右键单击要为其创建备份计划的数据库所在的配置文件，然后选择 * 计划备份 * 。
. 在 * 标签 * 中，输入备份的自定义名称。
+
名称中不得包含空格或特殊字符。如果不指定名称， SnapManager 会自动创建备份标签。

+
在 SnapManager 3.4 中，您可以修改 SnapManager 自动创建的备份标签。您可以编辑`override.default.backup.pattern`和`new.default.backup.pattern`配置变量以创建自己的默认备份标签模式。

. 可选：在* SnapVault Label"中、您必须在设置SnapVault 关系时输入在策略规则中指定的SnapMirror标签。
+

NOTE: 只有在创建配置文件时选择了 _SnapManager_cDOT_Vault_as 保护策略时， * SnapVault Label* 字段才会显示。

. 如果需要，选择 * 允许启动或关闭数据库 * 以修改数据库的状态。
+
此选项可确保如果数据库未处于创建备份所需的状态， SnapManager 会自动将数据库置于所需状态以完成此操作。

. 在*数据库*、*表空间*或*数据文件*到*备份*页面上、执行以下操作：
+
.. 选择 * 备份数据文件 * 可备份完整数据库，选定数据文件或选定表空间。
.. 选择 * 备份归档日志 * 可单独备份归档日志文件。
.. 如果要从已备份的活动文件系统中删除归档日志文件，请选择 * 复选框归档日志 * 。
+

NOTE: 如果为归档日志文件启用了 Flash Recovery Area （ FRA ），则 SnapManager 无法对归档日志文件进行修剪。

.. 如果要启用备份保护，请选择 * 保护备份 * 。
+
只有在创建配置文件时选择了保护策略时，才会启用此选项。

.. 从 * 类型 * 下拉列表中，选择要创建的备份类型（脱机或联机）。
+
如果选择_Auto_、SnapManager 将根据数据库的当前状态创建备份。

.. 从 * 保留类 * 下拉列表中，选择保留类。
.. 如果要确保备份的文件未损坏，请选中 * 使用 Oracle DBVERIFY 实用程序验证备份 * 复选框。


. 在 * 计划名称 * 字段中，输入计划的自定义名称。
+
名称中不得包含空格。

. 在*配置备份计划*页面上、执行以下操作：
+
.. 从 * 执行此操作 * 下拉列表中，选择备份计划的频率。
.. 在 * 开始日期 * 字段中，指定要启动备份计划的日期。
.. 在 * 开始时间 * 字段中，指定要启动备份计划的时间。
.. 指定创建备份的间隔。
+
例如，如果选择频率为每小时，并将间隔指定为 2 ，则备份将每 2 小时计划一次。



. 在*任务启用*页面上、指定是否要在备份操作完成前后执行任务。
. 在*执行备份计划操作*页面上、验证相关信息并单击*计划*。
. 单击 * 完成 * 以关闭向导。
+
如果操作失败，请单击 * 操作详细信息 * 以查看导致操作失败的原因。



* 相关信息 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["《适用于SAP的SnapManager 3.4.1 UNIX管理指南》"^]
