---
permalink: unix-installation-cmode/task-smsap-isg-create-a-profile-for-your-database.html 
sidebar: sidebar 
keywords: create, profile, database, perform, operation, contain, information, reference, multiple 
summary: 您必须为数据库创建配置文件，才能对该数据库执行任何操作。配置文件包含有关数据库的信息，并且只能引用一个数据库；但是，一个数据库可以由多个配置文件引用。使用一个配置文件创建的备份无法从其他配置文件访问，即使这两个配置文件都与同一数据库相关联也是如此。 
---
= 为数据库创建配置文件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须为数据库创建配置文件，才能对该数据库执行任何操作。配置文件包含有关数据库的信息，并且只能引用一个数据库；但是，一个数据库可以由多个配置文件引用。使用一个配置文件创建的备份无法从其他配置文件访问，即使这两个配置文件都与同一数据库相关联也是如此。



== 您将需要什么

您必须确保目标数据库详细信息包含在`/etc/oratab`文件中。



== 关于此任务

以下步骤显示了如何使用 SnapManager UI 为数据库创建配置文件。如果愿意，您也可以使用命令行界面。

有关如何使用命令行界面创建配置文件的信息、请参见适用于UNIX_的_SAP SnapManager 管理指南。

.步骤
. 在存储库树中，右键单击存储库或主机，然后选择 * 创建配置文件 * 。
. 在*配置文件配置信息*页面上、输入配置文件的自定义名称和密码。
. 在*数据库配置信息*页面上、输入以下信息：
+
|===
| 在此字段中 ... | 执行此操作 ... 


 a| 
* 数据库名称 *
 a| 
输入要备份的数据库的名称。



 a| 
* 数据库 SID*
 a| 
输入数据库的安全 ID （ SID ）。数据库名称和数据库 SID 可以相同。



 a| 
* 主机 *
 a| 
输入目标数据库所在主机的 IP 地址。如果在域名系统（ DNS ）中指定了主机名，则也可以指定主机名。



 a| 
* 主机帐户 *
 a| 
输入目标数据库的 Oracle 用户名。用户的默认值为 oracle 。



 a| 
* 主机组 *
 a| 
输入 Oracle 用户组名称。默认值为 dba 。

|===
. 在*数据库连接信息*页面上、选择以下选项之一：
+
|===
| 选择此项 ... | 如果您要 ... 


 a| 
* 使用操作系统身份验证 *
 a| 
使用操作系统维护的凭据对访问数据库的用户进行身份验证。



 a| 
* 使用数据库身份验证 *
 a| 
允许 Oracle 使用密码文件身份验证对管理用户进行身份验证。输入相应的数据库连接信息。

** 在 * SYSDBA 特权用户名 * 字段中，输入具有管理权限的数据库管理员的名称。
** 在 * 密码 * 字段中，输入数据库管理员的密码。
** 在 * 端口 * 字段中，输入用于连接到数据库所在主机的端口号。
+
默认值为1527。





 a| 
* 使用 ASM 实例身份验证 *
 a| 
允许自动存储管理（ Automatic Storage Management ， ASM ）数据库实例对管理用户进行身份验证。输入相应的 ASM 实例身份验证信息。

** 在 * SYSDBA/SYSASM 特权用户名 * 字段中，输入具有管理权限的 ASM 实例管理员的用户名。
** 在 * 密码 * 字段中，输入管理员的密码。


|===
+
[NOTE]
====
只有当数据库主机上有ASM实例时、才能选择ASM身份验证模式。

====
. 在* RMAN配置信息*页面上、选择以下选项之一：
+
|===
| 选择此项 ... | 条件 


 a| 
* 请勿使用 RMAN*
 a| 
您不使用 RMAN 管理备份和还原操作。



 a| 
通过控制文件使用 RMAN
 a| 
您正在使用控制文件管理 RMAN 存储库。



 a| 
* 通过恢复目录使用 RMAN
 a| 
您正在使用恢复目录数据库管理 RMAN 存储库。输入有权访问恢复目录数据库的用户名，密码以及管理透明网络承印商（ Network Substrate ， TNS ）连接的数据库的 Oracle 网络服务名称。

|===
. 在*快照命名信息*页面上、选择变量以指定Snapshot副本的命名格式。
+
您必须在命名格式中包含 SMID 变量。_SMID_变量创建唯一的Snapshot标识符。

. 在*策略设置*页面上、执行以下操作：
+
.. 输入每个保留类的保留计数和持续时间。
.. 从 * 保护策略 * 下拉列表中，选择保护策略。
+
您必须根据是否已建立 SnapMirror 或 SnapVault 关系选择 _SnapManager_cDOT_Mirror_ 或 _SnapManager_cDOT_Vault_policies 。

.. 如果要单独备份归档日志，请选中 * 单独备份归档日志 * 复选框，指定保留期限并选择保护策略。
+
您可以选择与数据文件关联的策略不同的策略。例如，如果已为数据文件选择 _SnapManager_cDOT_Mirror_ ，则可以为归档日志选择 _SnapManager_cDOT_Vault__ 。



. 在*配置通知设置*页面上、指定电子邮件通知设置。
. 在*历史记录配置信息*页面上、选择一个选项以维护SnapManager 操作历史记录。
. 在*执行配置文件创建操作*页面上、验证信息并单击*创建*。
. 单击 * 完成 * 以关闭向导。
+
如果操作失败，请单击 * 操作详细信息 * 以查看导致操作失败的原因。



* 相关信息 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["《适用于SAP的SnapManager 3.4.1 UNIX管理指南》"^]
