---
permalink: unix-installation-7mode/task-smsap-isg-configure-the-snapmanager-repository.html 
sidebar: sidebar 
keywords: configure, snapmanager, repository, database, instance, store, manage, configuring 
summary: 您必须在存储库数据库实例中配置 SnapManager 存储库。存储库数据库用于存储由 SnapManager 管理的数据库的元数据。 
---
= 配置SnapManager 存储库
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须在存储库数据库实例中配置 SnapManager 存储库。存储库数据库用于存储由 SnapManager 管理的数据库的元数据。

* 您需要的内容 *

* 您必须已创建存储库数据库实例。
* 您必须已为存储库数据库实例创建具有所需权限的 Oracle 用户。
* 您必须已在`tnsnames.ora`文件中包含存储库数据库实例详细信息。


* 关于此任务 *

您可以从 SnapManager 用户界面（ UI ）或命令行界面（ CLI ）配置 SnapManager 存储库。以下步骤显示了如何使用 SnapManager UI 创建存储库。如果愿意，您也可以使用命令行界面。

有关如何使用命令行界面创建存储库的信息、请参见适用于UNIX_的_SAP SnapManager 管理指南。

. 在 SnapManager UI 的左窗格中，右键单击 * 存储库 * 。
. 选择 * 创建新存储库 * ，然后单击 * 下一步 * 。
. 在*存储库数据库配置信息*窗口中、输入以下信息：
+
|===
| 在此字段中 ... | 执行此操作 ... 


 a| 
* 用户名 *
 a| 
输入为存储库数据库实例创建的用户的名称。



 a| 
* 密码 *
 a| 
输入密码。



 a| 
* 主机 *
 a| 
输入创建存储库数据库实例的主机的 IP 地址。



 a| 
* 端口 *
 a| 
输入用于连接到存储库数据库实例的端口。默认端口为 1521 。



 a| 
* 服务名称 *
 a| 
输入 SnapManager 用于连接到存储库数据库实例的名称。根据`tnsnames.ora`文件中包含的详细信息、此名称可能是短服务名称或完全限定服务名称。

|===
. 在*执行存储库添加操作*窗口中、查看配置摘要并单击*添加*。
+
如果操作失败，请单击 * 操作详细信息 * 选项卡以查看导致操作失败的原因。错误详细信息也会记录在位于/var/log/smsap的操作日志中。

. 单击 * 完成 * 。
+
存储库将列在左窗格中的 * 存储库 * 树下。如果未看到存储库，请右键单击 * 存储库 * ，然后单击 * 刷新 * 。



* 相关信息 *

https://library.netapp.com/ecm/ecm_download_file/ECMP12481453["《适用于SAP的SnapManager 3.4.1 UNIX管理指南》"^]
